---
settings:
  name: Release Notes
  platform: cloud
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
  rss_page: whats-new.html
  langs: zh-cn,us-en,ja-jp,ko-kr,zh-tw,de-de,es-es,fr-fr,it-it
sidebar:
  entries:
  - title: BlueXP发行说明
    url: "/index.html"
  - title: 最近更改
    url: "/whats-new.html"
  - title: BlueXP索引
    url: "/release-notes-index.html"
homepage:
  tiles:
  - title: 新增功能
    links:
    - title: BlueXP中的最新变更
      url: whats-new.html
  - title: 发行说明（按服务）
    links:
    - title: 发行说明索引
      url: release-notes-index.html
  - title: 博客社区
    links:
    - title: NetApp 社区
      url: https://community.netapp.com/t5/Public-Cloud-Services/ct-p/CDS
    - title: BlueXP博客
      url: https://bluexp.netapp.com/blog
    - title: 云网络研讨会
      url: https://bluexp.netapp.com/events
product-family:
  name: BlueXP
  repo: cloud-manager-family
  sidebar_label: 所有BlueXP文档
