---
sidebar: sidebar 
permalink: whats-new.html 
keywords: 'what"s new, features, new, release notes, enhancements, fixes, new features,cloud manager, bluexp, cloud volumes ontap, licenses, digital wallet, subscriptions, cloud backup, cloud tiering, data sense, ransomware, connector, amazon fsx for ontap, azure netapp files, cloud sync, e-series, global file cache, google cloud, disaster recovery, backup and recovery, classification, copy and sync, edge cache, edge caching, volume caching, ontap clusters, alerts, identity and access management, iam' 
summary: 了解作为BlueXP平台一部分的云服务的最新变更。 
---
= BlueXP中的最新变更
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
了解作为BlueXP平台一部分的云服务的最新变更。有关完整的版本历史记录、请转到 link:release-notes-index.html["完整的发行说明"] 针对每个服务。



== 管理功能

本节介绍与BlueXP管理功能相关的新功能：帐户、连接器、云提供商凭据等。



=== 2025年4月14日



==== 连接器3.9.51

此版本的BlueXP Connector包括一些小的安全改进和错误修复。

目前、3.9.51版本可用于标准模式和受限模式。



==== BlueXP  身份和访问管理(IAM)

* 不具有组织管理员、文件夹或项目管理员的用户必须分配一个防反向程序保护角色、才能访问防反向程序保护。您可以为用户分配以下两个角色之一：勒索软件保护管理员或勒索软件保护查看器。
* 没有组织管理员、文件夹管理员或项目管理员的用户必须分配Keystone角色、才能访问Keystone。您可以为用户分配以下两个角色之一：Keystone管理员或Keystone查看器。
+
link:https://docs.netapp.com/us-en/bluexp-setup-admin/reference-iam-predefined-roles.html["了解访问角色。"^]

* 如果您具有组织管理员、文件夹或项目管理员角色、则现在可以将Keystone订阅与IAM项目相关联。通过将Keystone订阅与IAM项目关联起来、您可以在BlueXP  中控制对Keystone的访问。




=== 2025年3月28日



==== 专用模式版本(3.9.50)

现在、可从下载新的专用模式版本 https://mysupport.netapp.com/site/downloads["NetApp 支持站点"^]

3.9.50版本包括对以下BlueXP  组件和服务的更新。

[cols="3*"]
|===
| 组件或服务 | 此版本包含的版本 | 自上一个专用模式版本以来的更改 


| 连接器 | 3.9.50 3.9.49 | 转到 https://docs.netapp.com/us-en/bluexp-setup-admin/whats-new.html#connector-3-9-50["BlueXP  连接器页面中的新增功能"]、并参阅3.9.50和3.9.49中包含的更改。 


| 备份和恢复 | 2025年3月17日 | 转到 https://docs.netapp.com/us-en/bluexp-backup-recovery/whats-new.html["BlueXP  备份和恢复页面中的新增功能"^]、并参考2024年3月版本中包含的更改。 


| 分类 | 2025年3月10日(版本1.41) | 转到 https://docs.netapp.com/us-en/bluexp-classification/whats-new.html["BlueXP  分类页面中的新增功能"^]、并参阅1.38 1.371.41版本中包含的更改。 
|===
有关专用模式的更多详细信息、包括如何升级、请参见以下内容：

* https://docs.netapp.com/us-en/bluexp-setup-admin/concept-modes.html["了解私有模式"]
* https://docs.netapp.com/us-en/bluexp-setup-admin/task-quick-start-private-mode.html["了解如何在私有模式下开始使用BlueXP"]
* https://docs.netapp.com/us-en/bluexp-setup-admin/task-upgrade-connector.html["了解如何在使用私有模式时升级连接器"]




=== 2025年3月10日



==== 连接器3.9.50

此版本的BlueXP Connector包括一些小的安全改进和错误修复。

目前、3.9.50版本可用于标准模式和受限模式。



==== BlueXP  提供NetApp Keystone测试版

NetApp Keystone很快将从BlueXP  发布、目前处于测试阶段。您可以从BlueXP  的左侧导航栏访问NetApp Keystone测试版的注册页面。



== 警报



=== 2024年10月7日



==== BlueXP  警报列表页面

您可以快速识别容量低或性能低的ONTAP集群、评估可用性范围并识别安全风险。您可以查看与容量、性能、保护、可用性、安全性和配置相关的警报。



==== 警报详细信息

您可以深入了解警报详细信息并查找建议。



==== 查看链接到ONTAP系统管理器的集群详细信息

通过BlueXP  警报、您可以查看与ONTAP存储环境关联的警报、并深入查看链接到ONTAP系统管理器的详细信息。

https://docs.netapp.com/us-en/bluexp-alerts/concept-alerts.html["了解BlueXP  警报"](英文)



== 适用于 ONTAP 的 Amazon FSX



=== 2025年3月30日



==== IAM：SimulatePermission Policy权限更新

现在、当您添加其他AWS帐户凭据或添加新工作负载功能(例如GenAI工作负载)时、您可以从BlueXP  控制台管理此 `iam:SimulatePrincipalPolicy`权限。

link:https://docs.netapp.com/us-en/workload-setup-admin/permissions-reference.html#change-log["权限引用更改日志"^]



=== 2025年3月2日



==== Tracker中的CloudShell事件

无论何时使用CloudShell从BlueXP  工作负载执行FSx for ONTAP操作、事件都会显示在Tracker中。

link:https://docs.netapp.com/us-en/bluexp-fsx-ontap/use/task-monitor-operations.html["了解如何在BlueXP  中监控和跟踪FSx for ONTAP操作"^]



=== 2025年2月2日



==== 将FSx for ONTAP文件系统与BlueXP  中的工作空间相关联

在2024年11月集成BlueXP  后、新创建的适用于ONTAP文件系统的FSx未与BlueXP  中的一个工作空间关联。现在、当您创建或发现FSx for ONTAP文件系统时、这些文件系统将与BlueXP  帐户中的一个工作空间相关联。

如果您现有的FSx for ONTAP文件系统未与工作空间关联、我们将帮助您将其与BlueXP  中的工作空间关联。您可以link:https://docs.netapp.com/us-en/bluexp-setup-admin/task-get-help.html#create-a-case-with-netapp-support["向NetApp支持部门创建案例"^]从BlueXP  控制台中执行此操作。选择*Workload Factory作为服务。



==== 从BlueXP  画布中删除文件系统

现在、您可以从BlueXP  画布中的工作空间中删除FSx for ONTAP文件系统。此操作会将文件系统与一个工作空间解除关联、以便您可以将其与同一BlueXP  帐户中的另一个工作空间相关联。

link:https://docs.netapp.com/us-en/bluexp-fsx-ontap/use/task-remove-filesystem.html["了解如何在BlueXP  中从工作空间中删除FSx for ONTAP文件系统"^]



==== 跟踪器可用于监控和跟踪操作

追踪器是一项新的监控功能、可在BlueXP  Amazon FSx for NetApp ONTAP中使用。您可以使用Tracker监控和跟踪凭据、存储和链接操作的进度和状态、查看操作任务和子任务的详细信息、诊断任何问题或故障、编辑失败操作的参数以及重试失败操作。

link:https://docs.netapp.com/us-en/bluexp-fsx-ontap/use/task-monitor-operations.html["了解如何在BlueXP  中监控和跟踪FSx for ONTAP操作"^]



==== BlueXP  工作负载中提供了CloudShell

当您在BlueXP  控制台中的BlueXP  工作负载中时、可以使用CloudShell。通过CloudShell、您可以使用在BlueXP  帐户中提供的AWS和ONTAP凭据、并在类似于Shell的环境中执行AWS命令行界面命令或ONTAP命令行界面命令。

link:https://docs.netapp.com/us-en/workload-setup-admin/use-cloudshell.html["使用CloudShell"^]



== Amazon S3存储



=== 2023年3月5日



==== 能够从BlueXP添加新存储分段

您可以在BlueXP Canvas上查看Amazon S3存储分段已有一段时间了。现在、您可以直接从BlueXP  添加新存储分段并更改现有存储分段的属性。 https://docs.netapp.com/us-en/bluexp-s3-storage/task-add-s3-bucket.html["了解如何添加新的Amazon S3存储分段"](英文)。



== Azure Blb存储



=== 2023年6月5日



==== 能够从BlueXP添加新存储帐户

您已有一段时间可以在BlueXP Canvs上查看Azure Blb Storage了。现在、您可以直接从BlueXP  添加新存储帐户并更改现有存储帐户的属性。 https://docs.netapp.com/us-en/bluexp-blob-storage/task-add-blob-storage.html["了解如何添加新的Azure Blb存储帐户"](英文)。



== Azure NetApp Files



=== 2025年1月13日



==== BlueXP  现在支持网络功能

现在、从BlueXP  在Azure NetApp Files中配置卷时、您可以指示网络功能。这与本机Azure NetApp Files中提供的功能一致。



=== 2024年6月12日



==== 需要新权限

现在、要从BlueXP管理Azure NetApp Files卷、需要以下权限：

Microsoft.Network/virtualNetworks/subnets/read

读取虚拟网络子网需要此权限。

如果您当前正在从BlueXP管理Azure NetApp Files、则需要将此权限添加到与先前创建的Microsoft Entra应用程序关联的自定义角色。

https://docs.netapp.com/us-en/bluexp-azure-netapp-files/task-set-up-azure-ad.html["了解如何设置Microsoft Entra应用程序和查看自定义角色权限"](英文)



=== 2024年4月22日



==== 不再支持卷模板

您无法再使用模板创建卷。此操作与BlueXP修复服务关联、此服务不再可用。



== 备份和恢复



=== 2025年3月17日

此BlueXP  备份和恢复版本包含以下更新。



==== SMB快照浏览

此BlueXP  备份和恢复更新解决了客户无法在SMB环境中浏览本地快照的问题。



==== AWS GovCloud环境更新

此BlueXP  备份和恢复更新修复了由于TLS证书错误而导致UI无法连接到AWS GovCloud环境的问题。已使用BlueXP  连接器主机名而非IP地址解决此问题。



==== 备份策略保留限制

以前、BlueXP  备份和恢复用户界面会将备份限制为999个副本、而命令行界面则允许更多副本。现在、您最多可以将4、000个卷连接到一个备份策略、并将1、018个未连接到备份策略的卷包括在内。此更新包含可防止超过这些限制的其他验证。



==== SnapMirror云重新同步

此更新可确保在删除SnapMirror关系后、无法从不受支持的ONTAP版本的BlueXP  备份和恢复启动SnapMirror云重新同步。



=== 2025年2月21日

此BlueXP  备份和恢复版本包含以下更新。



==== 高性能索引编制

BlueXP  备份和恢复引入了一项经过更新的索引编制功能、可提高源工作环境中数据的索引编制效率。新的索引编制功能包括更新用户界面、提高搜索和还原数据方法的性能、升级全局搜索功能以及更好的可扩展性。

以下是改进的细分：

* *文件夹整合*：更新后的版本使用包含特定标识符的名称将文件夹分组在一起，使索引编制过程更顺畅。
* *镶木地板文件缩减*：更新后的版本减少了为每个卷编制索引所使用的文件数量，从而简化了流程，并且不再需要额外的数据库。
* *通过更多会话实现横向扩展*：新版本增加了更多会话来处理索引编制任务、从而加快了处理速度。
* *支持多个索引容器*：新版本使用多个容器来更好地管理和分发索引任务。
* *拆分索引工作流*：新版本将索引编制过程分为两部分，提高了效率。
* *改进的并发性*：新版本可以同时删除或移动目录，从而加快索引编制过程。


.谁可以从该功能中受益？
所有新客户均可使用新的索引功能。

.如何启用索引编制？
在使用搜索和还原方法还原数据之前、您需要在计划从中还原卷或文件的每个源工作环境上启用"索引编制"。这样、索引目录就可以跟踪每个卷和每个备份文件、从而使搜索快速高效。

在执行搜索和还原时、通过选择"启用索引"选项、在源工作环境中启用索引。

有关详细信息，请参见文档 https://docs.netapp.com/us-en/bluexp-backup-recovery/task-restore-backups-ontap.html#restore-ontap-data-using-search-restore["如何使用搜索和恢复来恢复ONTAP数据()"]。

.支持的扩展
新的索引编制功能支持以下功能：

* 不到3分钟即可实现全局搜索效率
* 最多50亿个文件
* 每个集群最多5000个卷
* 每个卷最多10万个快照
* 基线索引编制的最长时间不超过7天。实际时间因环境而异。




==== 全局搜索性能改进

此版本还对全局搜索性能进行了增强。现在、您将看到进度指示器和更详细的搜索结果、包括文件计数和搜索所用时间。用于搜索和索引编制的专用容器可确保在五分钟内完成全局搜索。

请注意以下与全局搜索相关的注意事项：

* 不会对标记为每小时的快照执行新索引。
* 新的索引编制功能仅适用于FlexVol上的快照、不适用于FlexGroup上的快照。




=== 2024年11月22日

此BlueXP  备份和恢复版本包含以下更新。



==== SnapLock Compliance和SnapLock Enterprise保护模式

现在、BlueXP  备份和恢复可以备份使用SnapLock Compliance或SnapLock Enterprise保护模式配置的FlexVol和FlexGroup内部卷。要获得此支持、集群必须运行ONTAP 9.14或更高版本。从ONTAP 9.11.1版开始、支持使用SnapLock企业模式备份FlexVol卷。早期版本的ONTAP不支持备份SnapLock保护卷。

请参见中支持的卷的完整列表 https://docs.netapp.com/us-en/bluexp-backup-recovery/concept-ontap-backup-to-cloud.html["了解有关BlueXP备份和恢复的信息"]。



==== "卷"页面上的"搜索和还原过程索引"

在使用搜索和还原之前、您需要在要从中还原卷数据的每个源工作环境上启用"索引编制"。这样、"已创建目录"就可以跟踪每个卷的备份文件。此时、卷页面将显示索引编制状态：

* Indexed：卷已编制索引。
* 进行中
* 未为其提供过任何服务
* 索引编制已暂停
* 错误
* 未启用




== 分类



=== 2025年4月14日



==== 1.42 版

此BlueXP  分类版本包括：

.针对工作环境进行批量扫描
BlueXP  分类现在支持对工作环境执行批量操作。您可以选择启用映射扫描、启用映射和分类扫描、禁用扫描或跨工作环境中的卷创建自定义配置。如果您为单个卷进行选择、则会覆盖批量选择。要执行批量操作，请导航到**配置**页并进行选择。

.在本地下载调查报告
BlueXP  分类现在支持在本地下载数据调查报告以在浏览器中查看。如果您选择本地选项、则数据调查仅以CSV格式提供、并且仅显示前10、000行数据。

有关详细信息，请参见 link:task-investigate-data.html#create-the-data-investigation-report["根据BlueXP  分类调查存储在您的组织中的数据"]。



=== 2025年3月10日



==== 1.41 版

此BlueXP  分类版本包括一些常规改进和错误修复。它还包括：

.扫描状态
现在、BlueXP  分类可跟踪卷上_initial-_映射和分类扫描的实时进度。单独的渐进式条可跟踪映射和分类扫描、显示扫描总文件的百分比。您也可以将鼠标悬停在进度条上以查看扫描的文件数和总文件数。跟踪扫描状态可更深入地了解扫描进度、使您能够更好地规划扫描并了解资源分配。

要查看扫描的状态，请导航到BlueXP  分类中的**配置**，然后选择**工作环境配置**。每个卷的进度将以行显示。



=== 2025年2月19日



==== 1.40 版

此BlueXP  分类版本包含以下更新。

.支持RHEL 9.5
除了先前支持的版本之外、此版本还支持Red Hat Enterprise Linux v9.5。这适用于BlueXP  分类的任何手动内部安装、包括非公开站点部署。

以下操作系统要求使用Podman容器引擎、并要求使用BlueXP  分类版本1.3或更高版本：Red Hat Enterprise Linux版本8.8、8.10、9.0、9.1、9.2、9.3、9.4和9.5。

.确定仅映射扫描的优先级
执行仅映射扫描时、您可以确定最重要扫描的优先级。如果您有许多工作环境、并希望确保首先完成高优先级扫描、则此功能会很有帮助。

默认情况下、扫描会根据启动顺序进行排队。现在、您可以将扫描移动到队列的前面、从而确定扫描的优先级。可以确定多个扫描的优先级。优先级按先入先出的顺序指定、这意味着您优先处理的第一个扫描将移至队列的前端；您优先处理的第二个扫描将成为队列中的第二个扫描、依此类推。

优先权是一次性授予的。按默认顺序自动重新选择映射数据。

优先级限制为link:concept-cloud-compliance.html["仅映射扫描"]；它不适用于地图扫描和分类扫描。

有关详细信息，请参见 link:task-managing-repo-scanning.html#prioritize-scans["确定扫描优先级"]。

.重试所有扫描
BlueXP  分类现在支持批量重试所有失败的扫描。

现在可以使用**重试全部**功能在批处理操作中重新尝试扫描。如果分类扫描因网络中断等临时问题而失败、您可以使用一个按钮同时重试所有扫描、而不是逐个重试。可以根据需要多次重试扫描。

重试所有扫描：

. 从BlueXP  分类菜单中，选择*Configuration*。
. 要重试所有失败的扫描，请选择*重试所有扫描*。


.提高了分类模型的准确性
的机器学习模型准确性link:https://docs.netapp.com/us-en/bluexp-classification/reference-private-data-categories.html#types-of-sensitive-personal-datapredefined-categories["预定义的类别"]提高了11%。



=== 2025年1月22日



==== 1.39 版

此BlueXP  分类版本更新了数据调查报告的导出流程。此导出更新适用于对数据执行其他分析、为数据创建其他可视化效果或与他人共享数据调查结果。

以前、数据调查报告导出限制为10、000行。此版本已删除限制、您可以导出所有数据。通过此更改、您可以从数据调查报告导出更多数据、从而提高数据分析的灵活性。

您可以选择工作环境、卷、目标文件夹以及JSON或CSV格式。导出的文件名包含一个时间戳、可帮助您确定数据的导出时间。

支持的工作环境包括：

* Cloud Volumes ONTAP
* 适用于 ONTAP 的 FSX
* ONTAP
* 共享组


从数据调查报告导出数据时存在以下限制：

* 要下载的最大记录数为5亿。每种类型(文件、目录和表)
* 100万条记录预计需要大约35分钟才能导出。


有关数据调查和报告的详细信息，请参见 https://docs.netapp.com/us-en/bluexp-classification/task-investigate-data.html["调查存储在组织中的数据"]。



=== 2024年12月16日



==== 1.38 版

此BlueXP  分类版本包括一些常规改进和错误修复。



== Cloud Volumes ONTAP



=== 2025年4月14日



==== 通过Google Cloud中的API自动创建Storage VM

现在、您可以使用BlueXP  API在Google Cloud中自动创建Storage VM。您一直在Cloud Volumes ONTAP高可用性(HA)配置中使用此功能、现在也可以在单节点部署中使用此功能。通过使用BlueXP  API、您可以轻松地在Google Cloud环境中创建、重命名和删除其他提供数据的Storage VM、而无需手动配置所需的网络接口、LUN和管理LUN。这种自动化可简化Storage VM的管理过程。

https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/task-managing-svms-gcp.html["在Google Cloud中管理为Cloud Volumes ONTAP提供数据的Storage VM"^]



=== 2025年3月28日



==== 为Cloud Volumes ONTAP 9.14.1启用了专用模式部署

现在、您可以在AWS、Azure和Google Cloud中以私有模式部署Cloud Volumes ONTAP 9.14.1。Cloud Volumes ONTAP 9.14.1的单节点和高可用性(HA)部署均启用了专用模式。

有关私有模式部署的详细信息，请参见https://docs.netapp.com/us-en/bluexp-setup-admin/concept-modes.html#restricted-mode["了解BlueXP部署模式"^]。



=== 2025年3月12日



==== Azure中的多可用性区域部署支持新区域

以下地区现在支持在适用于Cloud Volumes ONTAP 9.12.1 GA及更高版本的Azure中部署HA多可用性区域：

* 位于美国中部
* 美国弗吉尼亚州政府(美国政府区域-弗吉尼亚州)


有关所有地区的列表，请参阅 https://bluexp.netapp.com/cloud-volumes-global-regions["Azure下的全局区域映射"^]。



== 适用于 Google Cloud 的 Cloud Volumes Service



=== 2020年9月9日



==== 支持适用于 Google Cloud 的 Cloud Volumes Service

现在、您可以直接从BlueXP管理适用于Google Cloud的Cloud Volumes Service ：

* 设置和创建工作环境
* 为 Linux 和 UNIX 客户端创建和管理 NFSv3 和 NFSv4.1 卷
* 为 Windows 客户端创建和管理 SMB 3.x 卷
* 创建，删除和还原卷快照




== 复制和同步



=== 2025年2月2日



==== 为数据代理提供了新的操作系统支持

现在、运行Red Hat Enterprise 9.4、Ubuntu 23.04和Ubuntu 24.04的主机支持数据代理。

https://docs.netapp.com/us-en/bluexp-copy-sync/task-installing-linux.html#linux-host-requirements["查看Linux主机要求"](英文)



=== 2024年10月27日



==== 错误修复

我们更新了BlueXP复制和同步服务以及数据代理以修复一些错误。新的数据代理版本为1.0.56。



=== 2024年9月16日



==== 错误修复

我们更新了BlueXP复制和同步服务以及数据代理以修复一些错误。新的数据代理版本为1.0.55。



== 数字顾问



=== 2025年3月5日



==== Upgrade Advisor

* 现在、您可以使用磁盘认证包(DQP)根据预定义的运行状况和性能标准自动更新磁盘控制器和存储设备固件。这样可以减少潜在故障并提高整体系统可靠性。
* 引入了时区数据库(DB)、用于自动保持系统与最新时区定义保持一致。这样可以确保即使时区规则发生更改、依赖时间的操作也能顺利进行。




=== 2024年12月12日



==== Upgrade Advisor

现在、您可以查看建议进行更新的存储固件、ARP/固 件和自动软件包(Autonomous SP Package、BMC)。link:https://docs.netapp.com/us-en/active-iq/view-firmware-update-recommendations.html["了解如何查看固件更新建议"](英文)



=== 2024年12月4日



==== AutoSupport小工具

AutoSupport小工具已添加到主信息板屏幕中、用于提醒客户与AutoSupport状态相关的问题。



== 数字电子钱包



=== 2025年3月10日



==== 删除订阅的功能

如果您取消订阅、现在可以从电子钱包中删除订阅。



==== 查看Marketplace订阅的已用容量

现在、在查看PAYGO订阅时、您可以查看此订阅的已用容量。



=== 2025年2月10日

BlueXP  数字钱包经过重新设计、易于使用、现在可提供额外的订阅和许可证管理。



==== 新增了"概述"信息板

数字钱包主页提供了一个更新的NetApp许可证和Marketplace订阅信息板、可以深入查看特定服务、许可证类型和所需操作。



==== 配置凭据订阅

现在、您可以通过BlueXP  数字钱包为提供商凭据配置订阅。通常、您在首次订阅Marketplace订阅或年度合同时会执行此操作。以前只能在"凭据"页面上更改订阅的凭据。



==== 将订阅与组织相关联

现在、您可以直接从数字钱包更新订阅关联到的组织。



==== 管理Cloud Volume ONTAP许可证

现在，您可以通过主页或*直接许可证*选项卡管理Cloud Volumes ONTAP许可证。使用*商城订阅*选项卡查看您的订阅信息。



=== 2024年3月5日



==== BlueXP灾难恢复

BlueXP数字钱包现在可用于管理BlueXP灾难恢复的许可证。您可以添加许可证、更新许可证以及查看有关已许可容量的详细信息。

https://docs.netapp.com/us-en/bluexp-digital-wallet/task-manage-data-services-licenses.html["了解如何管理BlueXP数据服务的许可证"]



=== 2023年7月30日



==== 使用情况报告增强功能

Cloud Volumes ONTAP使用情况报告现已有多项改进：

* 此时、TiB单元将包含在列名称中。
* 现在、包含了一个用于序列号的新_node (s)_字段。
* 现在、Storage VM使用情况报告下会包含一个新的_Workload Type_列。
* 现在、工作环境名称会包含在Storage VM和卷使用情况报告中。
* 卷类型_file_现在标记为_Primary (Read/Write)_。
* 卷类型_Secondary (DP)_现在标记为_Secondary (DP)_。


有关使用情况报告的详细信息、请参见 https://docs.netapp.com/us-en/bluexp-digital-wallet/task-manage-capacity-licenses.html#download-usage-reports["下载使用情况报告"]。



== 灾难恢复



=== 2025年4月16日

4.3 版



==== 按计划发现VM

BlueXP  灾难恢复每24小时执行一次发现。在此版本中、您现在可以自定义发现计划以满足您的需求、并在需要时减少对性能的影响。例如、如果VM数量很多、则可以将发现计划设置为每48小时运行一次。如果VM数量较少、则可以将发现计划设置为每12小时运行一次。

如果您不想计划发现、则可以禁用计划的发现选项、并随时手动刷新发现。

有关详细信息，请参见 https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/sites-add.html["添加vCenter Server站点"]。



==== 资源组数据存储库支持

以前、您只能按VM创建资源组。在此版本中、您可以按数据存储库创建资源组。在创建复制计划并为该计划创建资源组时、将列出数据存储库中的所有VM。如果您有大量VM并希望按数据存储库对其进行分组、则此功能非常有用。

您可以通过以下方式使用数据存储库创建资源组：

* 使用数据存储库添加资源组时、您可以看到数据存储库列表。您可以选择一个或多个数据存储库来创建资源组。
* 在创建复制计划并在此计划中创建资源组时、您可以看到数据存储库中的VM。


有关详细信息，请参见 https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/drplan-create.html["创建复制计划"]。



==== 免费试用或许可证到期通知

此版本会通知您免费试用版将在60天后过期、以确保您有时间获取许可证。此版本还会在许可证到期当天发出通知。



==== 服务更新通知

在此版本中、顶部会显示一个横幅、指示服务正在升级、并且此服务处于维护模式。升级服务时会显示此横幅、升级完成后此横幅将消失。虽然升级期间您可以继续在UI中工作、但无法提交新作业。计划作业将在更新完成且服务返回到生产模式后运行。



=== 2025年2月19日

4.2 版



==== ASA R2支持VMFS存储上的VM和数据存储库

此版本的BlueXP  灾难恢复支持对VMFS存储上的VM和数据存储库使用ASA R2。在ASA R2系统上、ONTAP软件支持基本SAN功能、但会删除SAN环境中不支持的功能。

此版本支持ASA R2的以下功能：

* 为主存储配置一致性组(仅限平面一致性组、表示只有一个级别没有分层结构)
* 备份(一致性组)操作、包括SnapMirror自动化


BlueXP  灾难恢复中对ASA R2的支持使用ONTAP 9.161。

虽然数据存储库可以挂载在ONTAP卷或ASA R2存储单元上、但BlueXP  灾难恢复中的资源组不能同时包含ONTAP和ASA R2中的数据存储库。您可以从资源组中的ONTAP或ASA R2选择数据存储库。



=== 2024年10月30日



==== 报告

现在、您可以生成并下载报告、以帮助您分析环境。预先设计的报告汇总故障转移和故障恢复、显示所有站点上的复制详细信息、并显示过去七天的作业详细信息。

请参阅 https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/reports.html["创建灾难恢复报告"]。



==== 30天免费试用

现在、您可以注册30天免费试用BlueXP  灾难恢复。以前、免费试用期限为90天。

请参阅 https://docs.netapp.com/us-en/bluexp-disaster-recovery/get-started/dr-licensing.html["设置许可"]。



==== 禁用和启用复制计划

先前版本对故障转移测试计划结构进行了更新、需要更新以支持每日和每周计划。此更新要求您禁用并重新启用所有现有复制计划、以便能够使用新的每日和每周故障转移测试计划。这是一次性要求。

方法如下：

. 从顶部菜单中选择*复制计划*。
. 选择一个计划、然后选择操作图标以显示下拉菜单。
. 选择 * 禁用 * 。
. 几分钟后，选择*Enable*。




==== 文件夹映射

现在、在创建复制计划并映射计算资源时、您可以映射文件夹、以便在为数据中心、集群和主机指定的文件夹中恢复VM。

有关详细信息，请参见 https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/drplan-create.html["创建复制计划"]。



==== 可用于故障转移、故障恢复和测试故障转移的VM详细信息

如果发生故障、并且您正在启动故障转移、执行故障恢复或测试故障转移、现在可以查看VM的详细信息并确定哪些VM未重新启动。

请参阅 https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/failover.html["将应用程序故障转移到远程站点"]。



==== VM启动延迟、按顺序启动

现在、在创建复制计划时、您可以为计划中的每个VM设置启动延迟。这样、您就可以设置VM的启动顺序、以确保优先级为一个的所有VM在后续优先级的VM启动之前都处于运行状态。

有关详细信息，请参见 https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/drplan-create.html["创建复制计划"]。



==== VM操作系统信息

创建复制计划时、您现在可以看到该计划中每个VM的操作系统。这有助于确定如何将虚拟机分组到一个资源组中。

有关详细信息，请参见 https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/drplan-create.html["创建复制计划"]。



==== VM名称别名

现在、在创建复制计划时、您可以向灾难恢复SIT上的虚拟机名称添加前缀和后缀。这样、您就可以为计划中的VM使用一个更具描述性的名称。

有关详细信息，请参见 https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/drplan-create.html["创建复制计划"]。



==== 清理旧快照

您可以删除超出指定保留数量的不再需要的任何快照。降低快照保留数量后、快照可能会逐渐累积、您现在可以将其删除以释放空间。您可以随时按需执行此操作、也可以在删除复制计划时执行此操作。

有关详细信息，请参见 https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/manage.html["管理站点、资源组、复制计划、数据存储库和虚拟机信息"]。



==== 协调快照

现在、您可以协调源和目标之间不同步的快照。如果在BlueXP  灾难恢复之外的目标上删除了快照、则可能会发生这种情况。该服务会每24小时自动删除一次源上的快照。但是、您可以按需执行此操作。通过此功能、您可以确保快照在所有站点之间保持一致。

有关详细信息，请参见 https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/manage.html["管理复制计划"]。



== E系列系统



=== 2022年9月18日



==== 支持E系列

现在、您可以直接从BlueXP发现E系列系统。通过发现E系列系统、您可以全面了解混合多云中的数据。



== 经济效率



=== 2024年5月15日



==== 禁用的功能

BlueXP  的一些经济效益功能已暂时禁用：

* 技术更新
* 添加容量




=== 2024年3月14日



==== 技术更新选项

如果您已有资产、并且希望确定是否需要更新某项技术、则可以使用BlueXP经济高效技术更新选项。您可以查看当前工作负载的简短评估并获取建议、或者如果您在过去90天内将AutoSupport日志发送给NetApp、则该服务现在可以提供工作负载模拟、以查看工作负载在新硬件上的运行情况。

您还可以添加工作负载并从模拟中排除现有工作负载。

以前、您只能对资产进行评估、并确定是否建议进行技术更新。

此功能现在是左侧导航栏中技术更新选项的一部分。

了解有关的更多信息 https://docs.netapp.com/us-en/bluexp-economic-efficiency/use/tech-refresh.html["评估技术更新"]。



=== 2023年11月8日



==== 技术更新

此版本的BlueXP经济高效功能提供了一个新选项、可用于评估您的资产并确定是否建议进行技术更新。此服务包括左侧导航栏中的新技术更新选项、可用于评估当前工作负载和资产的新页面以及可为您提供建议的报告。



== 边缘缓存

BlueXP  边缘缓存服务已于2024年8月7日被删除。



== Google Cloud 存储



=== 2023年7月10日



==== 可以通过BlueXP添加新存储分段并管理现有存储分段

您可以在BlueXP Canvs上查看Google Cloud Storage存储分段已有很长一段时间了。现在、您可以直接从BlueXP  添加新存储分段并更改现有存储分段的属性。 https://docs.netapp.com/us-en/bluexp-google-cloud-storage/task-add-gcp-bucket.html["了解如何添加新的Google Cloud存储分段"](英文)。



== Kubernetes

2024年8月7日、不再支持发现和管理Kubbernetes集群。



== 迁移报告

BlueXP  迁移报告服务已于2024年8月7日删除。



== 内部 ONTAP 集群



=== 2024年11月26日



==== 支持使用专用模式的ASA R2系统

现在、在私有模式下使用BlueXP  时、您可以发现NetApp ASA R2系统。从BlueXP  的3.9.46专用模式版本开始、可提供此支持。

* https://docs.netapp.com/us-en/asa-r2/index.html["详细了解ASA R2系统"^]
* https://docs.netapp.com/us-en/bluexp-setup-admin/concept-modes.html["了解BlueXP部署模式"^]




=== 2024年10月7日



==== 支持ASA R2系统

现在、如果在标准模式或受限模式下使用BlueXP 、则可以在BlueXP  中发现NetApp ASA R2系统。发现NetApp ASA R2系统并打开工作环境后、您将直接转到System Manager。

ASA R2系统没有其他可用的管理选项。您不能使用标准视图、也不能启用BlueXP服务。

在专用模式下使用BlueXP  时、不支持发现ASA R2系统。

* https://docs.netapp.com/us-en/asa-r2/index.html["详细了解ASA R2系统"^]
* https://docs.netapp.com/us-en/bluexp-setup-admin/concept-modes.html["了解BlueXP部署模式"^]




=== 2024年4月22日



==== 不再支持卷模板

您无法再使用模板创建卷。此操作与BlueXP修复服务关联、此服务不再可用。



== 运营故障恢复能力



=== 2023年4月2日



==== BlueXP  操作故障恢复能力服务

通过使用新的BlueXP操作故障恢复能力服务及其自动化IT操作风险修复建议、您可以在发生中断或故障之前实施建议的修复措施。

运营故障恢复能力是一项服务、可帮助您分析警报和事件、以保持服务和解决方案的运行状况、正常运行时间和性能。

link:https://docs.netapp.com/us-en/bluexp-operational-resiliency/get-started/intro.html["详细了解BlueXP操作故障恢复能力"]。



== 勒索软件保护



=== 2025年4月14日



==== 就绪演练报告

在此版本中、您可以查看勒索软件攻击就绪演练报告。通过准备工作演练、您可以模拟对新创建的示例工作负载的勒索软件攻击。然后、调查模拟的攻击并恢复示例工作负载。此功能通过测试警报通知、响应和恢复过程、帮助您了解在发生实际勒索软件攻击时您已做好准备。

有关详细信息，请参见 https://docs.netapp.com/us-en/bluexp-ransomware-protection/rp-start-simulate.html["进行勒索软件攻击准备演练"]。



==== 新的基于角色的访问控制角色和权限

以前、您可以根据用户的职责为其分配角色和权限、这有助于您管理用户对BlueXP  勒索软件保护的访问。在此版本中、BlueXP  勒索软件保护新增了两个角色、并更新了权限。新角色包括：

* 勒索软件保护管理员
* 勒索软件保护查看器


有关权限的详细信息，请参见 https://docs.netapp.com/us-en/bluexp-ransomware-protection/rp-reference-roles.html["BlueXP  勒索软件保护基于角色的功能访问"]。



==== 付款改进

此版本对付款流程进行了多项改进。

有关详细信息，请参见 https://docs.netapp.com/us-en/bluexp-ransomware-protection/rp-start-licenses.html["设置许可和付款选项"]。



=== 2025年3月10日



==== 模拟攻击并做出响应

在此版本中、模拟勒索软件攻击以测试您对勒索软件警报的响应。此功能通过测试警报通知、响应和恢复过程、帮助您了解在发生实际勒索软件攻击时您已做好准备。

有关详细信息，请参见 https://docs.netapp.com/us-en/bluexp-ransomware-protection/rp-start-simulate.html["进行勒索软件攻击准备演练"]。



==== 发现过程的增强功能

此版本对选择性发现和重新发现过程进行了增强：

* 在此版本中、您可以发现添加到先前选定工作环境中的新创建工作负载。
* 您也可以在此版本中选择_new_工作环境。此功能可帮助您保护添加到环境中的新工作负载。
* 您可以在最初的发现过程中或在设置选项中执行这些发现过程。


有关详细信息，请参阅 https://docs.netapp.com/us-en/bluexp-ransomware-protection/rp-start-discover.html["发现先前选定工作环境中新创建的工作负载"]和 https://docs.netapp.com/us-en/bluexp-ransomware-protection/rp-use-settings.html["使用设置选项配置功能"]。



==== 检测到高加密时引发警报

在此版本中、即使文件扩展名未更改、您也可以在工作负载上检测到高加密时查看警报。此功能使用ONTAP自动勒索软件保护(ARP) AI、可帮助您识别面临勒索软件攻击风险的工作负载。使用此功能并下载受影响文件的完整列表(无论是否更改扩展名)。

有关详细信息，请参见 https://docs.netapp.com/us-en/bluexp-ransomware-protection/rp-use-alert.html["响应检测到的勒索软件警报"]。



=== 2024年12月16日



==== 使用Data Infrastructure Insight存储工作负载安全性检测异常用户行为

在此版本中、您可以使用Data Infrastructure Insight存储工作负载安全性来检测存储工作负载中的异常用户行为。此功能可帮助您识别潜在的安全威胁并阻止潜在的恶意用户来保护您的数据。

有关详细信息，请参见 https://docs.netapp.com/us-en/bluexp-ransomware-protection/rp-use-alert.html["响应检测到的勒索软件警报"]。

在使用数据基础架构洞察存储工作负载安全性检测异常用户行为之前、您需要使用BlueXP  勒索软件保护*设置*选项来配置此选项。

请参阅 https://docs.netapp.com/us-en/bluexp-ransomware-protection/rp-use-settings.html["配置BlueXP勒索软件保护设置"]。



==== 选择要发现和保护的工作负载

在此版本中、您现在可以执行以下操作：

* 在每个Connector中、选择要发现工作负载的工作环境。如果您希望保护环境中的特定工作负载、而不是其他工作负载、则可以从该功能中受益。
* 在发现工作负载期间、您可以为每个连接器启用工作负载自动发现。通过此功能、您可以选择要保护的工作负载。
* 发现先前选定工作环境中新创建的工作负载。


请参阅 https://docs.netapp.com/us-en/bluexp-ransomware-protection/rp-start-discover.html["发现工作负载"]。



== 修复

BlueXP修复服务已于2024年4月22日删除。



== Replication



=== 2022年9月18日



==== 适用于ONTAP 到Cloud Volumes ONTAP 的FSX

现在、您可以将适用于ONTAP 的Amazon FSx文件系统中的数据复制到Cloud Volumes ONTAP。

https://docs.netapp.com/us-en/bluexp-replication/task-replicating-data.html["了解如何设置数据复制"]。



=== 2022年7月31日



==== FSX for ONTAP 作为数据源

现在、您可以将数据从适用于ONTAP 的Amazon FSX文件系统复制到以下目标：

* 适用于 ONTAP 的 Amazon FSX
* 内部 ONTAP 集群


https://docs.netapp.com/us-en/bluexp-replication/task-replicating-data.html["了解如何设置数据复制"]。



=== 2021年9月2日



==== 支持适用于 ONTAP 的 Amazon FSX

现在，您可以将数据从 Cloud Volumes ONTAP 系统或内部 ONTAP 集群复制到适用于 ONTAP 的 Amazon FSX 文件系统。

https://docs.netapp.com/us-en/bluexp-replication/task-replicating-data.html["了解如何设置数据复制"]。



== 软件更新



=== 2025年4月2日



==== 已缓解风险

现在、您可以在BlueXP  软件更新的摘要部分中查看操作系统更新可缓解的风险总数。这样、用户就可以评估其安装基础上的安全性和稳定性改进。



=== 2024年8月7日



==== ONTAP更新

BlueXP  软件更新服务通过降低风险并确保客户能够充分利用ONTAP功能、为用户提供无缝的更新体验。

详细了解 link:https://docs.netapp.com/us-en/bluexp-software-updates/get-started/software-updates.html["BlueXP  软件更新"]。



== StorageGRID



=== 2024年8月7日



==== 新的高级视图

从StorageGRID 11.8开始、您可以使用熟悉的网格管理器界面从BlueXP  管理StorageGRID系统。

https://docs.netapp.com/us-en/bluexp-storagegrid/task-administer-storagegrid.html["了解如何使用高级视图管理StorageGRID"](英文)



==== 能够审核和批准StorageGRID管理接口证书

现在、您可以在从BlueXP  发现StorageGRID系统时查看和批准StorageGRID管理接口证书。您还可以在发现的网格上查看和批准最新的StorageGRID管理接口证书。

https://docs.netapp.com/us-en/bluexp-storagegrid/task-discover-storagegrid.html["了解如何在系统发现期间查看和批准服务器证书。"]



=== 2022年9月18日



==== 支持StorageGRID

现在、您可以直接从BlueXP发现StorageGRID 系统。通过发现StorageGRID 、您可以全面了解混合多云中的数据。



== 分层



=== 2023年8月9日



==== 使用自定义前缀作为分段名称

过去、在定义存储分段名称时、您需要使用默认的"光纤 池"前缀、例如_Fabric池bucket1_。现在、您可以在为存储分段命名时使用自定义前缀。只有在将数据层到Amazon S3时、此功能才可用。 https://docs.netapp.com/us-en/bluexp-tiering/task-tiering-onprem-aws.html#prepare-your-aws-environment["了解更多信息。"]。



==== 在所有BlueXP连接器中搜索集群

如果使用多个连接器管理环境中的所有存储系统、则要实施分层的某些集群可能位于不同的连接器中。如果您不确定是哪个Connector管理某个集群、可以使用BlueXP分层跨所有连接器进行搜索。 https://docs.netapp.com/us-en/bluexp-tiering/task-managing-tiering.html#search-for-a-cluster-across-all-bluexp-connectors["了解更多信息。"]。



=== 2023年7月4日



==== 调整带宽以传输非活动数据

激活BlueXP分层后、ONTAP可以使用无限的网络带宽将非活动数据从集群中的卷传输到对象存储。如果您发现分层流量正在影响正常用户工作负载、则可以限制传输期间可使用的带宽量。 https://docs.netapp.com/us-en/bluexp-tiering/task-managing-tiering.html#changing-the-network-bandwidth-available-to-upload-inactive-data-to-object-storage["了解更多信息。"](英文)。



==== 通知中心中显示的层事件

现在、如果集群对其冷数据(包括未分层任何数据的集群)的分层不足20%、则分层事件"将其他数据从集群<name>分层到对象存储以提高存储效率"将显示为通知。

此通知是一个"建议"、可帮助您提高系统效率并节省存储成本。它提供了指向的链接 https://bluexp.netapp.com/cloud-tiering-service-tco["BlueXP分层总拥有成本和节省量计算器"^] 以帮助您计算成本节省。



=== 2023年4月3日



==== 已删除许可选项卡

已从BlueXP分层界面中删除许可选项卡。现在、您可以从BlueXP分层内部部署信息板访问按需购买(PAYGO)订阅的所有许可。此外、还提供了一个从该页面到BlueXP数字钱包的链接、可用于查看和管理任何BlueXP分层自带许可证(BYOL)。



==== 分层选项卡已重命名和更新

"集群信息板"选项卡已重命名为"集群"、"内部概述"选项卡已重命名为"内部部署信息板"。这些页面添加了一些信息、可帮助您评估是否可以通过其他分层配置优化存储空间。



== 卷缓存



=== 2023年6月4日



==== 卷缓存

卷缓存是ONTAP 9软件的一项功能、它是一项远程缓存功能、可简化文件分发、通过使资源更靠近用户和计算资源所在位置来减少WAN延迟、并降低WAN带宽成本。卷缓存可在远程位置提供永久性可写卷。您可以使用BlueXP卷缓存加快数据访问速度、或者从访问量较多的卷卸载流量。缓存卷非常适合读取密集型工作负载、尤其是客户端需要重复访问相同数据的情况。

借助BlueXP卷缓存、您可以缓存云、尤其是Amazon FSx for NetApp ONTAP、Cloud Volumes ONTAP以及作为工作环境的内部环境。

link:https://docs.netapp.com/us-en/bluexp-volume-caching/get-started/cache-intro.html["详细了解BlueXP卷缓存"]。



== 工作负载工厂



=== 2025年3月30日



==== CloudShell会报告ONTAP命令行界面命令的AI生成的错误响应

使用CloudShell时、每次发出ONTAP命令行界面命令并出现错误时、您都可以获得AI生成的错误响应、其中包括故障说明、故障原因和详细解决方案。

link:https://docs.netapp.com/us-en/workload-setup-admin/use-cloudshell.html["使用CloudShell"]



==== IAM：SimulatePermission Policy权限更新

现在、当您添加其他AWS帐户凭据或添加新工作负载功能(例如GenAI工作负载)时、您可以从工作负载出厂控制台管理此 `iam:SimulatePrincipalPolicy`权限。

link:https://docs.netapp.com/us-en/workload-setup-admin/permissions-reference.html#change-log["权限引用更改日志"]



=== 2025年2月2日



==== BlueXP  工作负载出厂控制台中提供了CloudShell

您可以从BlueXP  工作负载出厂控制台中的任何位置访问CloudShell。通过CloudShell、您可以使用在BlueXP  帐户中提供的AWS和ONTAP凭据、并在类似于Shell的环境中执行AWS命令行界面命令或ONTAP命令行界面命令。

link:https://docs.netapp.com/us-en/workload-setup-admin/use-cloudshell.html["使用CloudShell"]



==== 更新数据库的权限

现在，以下权限在_read_模式下可用于数据库： `iam:SimulatePrincipalPolicy`。

link:https://docs.netapp.com/us-en/workload-setup-admin/permissions-reference.html#change-log["权限引用更改日志"]



=== 2025年1月22日



==== BlueXP  工作负载出厂权限

现在、您可以查看BlueXP  工作负载工厂执行各种操作所使用的权限、这些操作从发现存储环境到为GenAI工作负载部署AWS资源(例如存储中的文件系统或知识库)不等。您可以查看存储、数据库、VMware和GenAI工作负载的IAM策略和权限。

link:https://docs.netapp.com/us-en/workload-setup-admin/permissions-reference.html["BlueXP  工作负载出厂权限"]
