---
sidebar: sidebar 
permalink: whats-new.html 
keywords: 'what"s new, features, new, release notes, enhancements, fixes, new features,cloud manager, bluexp, cloud volumes ontap, licenses, digital wallet, subscriptions, cloud backup, cloud tiering, data sense, ransomware, connector, amazon fsx for ontap, azure netapp files, cloud sync, e-series, global file cache, google cloud, disaster recovery, backup and recovery, classification, copy and sync, edge cache, edge caching, volume caching, ontap clusters, alerts, identity and access management, iam, recovery' 
summary: 了解作为BlueXP平台一部分的云服务的最新变更。 
---
= BlueXP中的最新变更
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
了解作为BlueXP平台一部分的云服务的最新变更。有关完整的版本历史记录、请转到 link:release-notes-index.html["完整的发行说明"] 针对每个服务。



== 管理功能

本节介绍与BlueXP管理功能相关的新功能：帐户、连接器、云提供商凭据等。



=== 2025年7月21日



==== 支持Google Cloud NetApp Volumes

您现在可以在BlueXP中查看Google Cloud NetApp Volumes 。 link:https://docs.netapp.com/us-en//bluexp-google-cloud-netapp-volumes/index.html/index.html["了解有关Google Cloud NetApp Volumes 的更多信息。"]



==== BlueXP  身份和访问管理(IAM)



===== Google Cloud NetApp Volumes的新访问角色

BlueXP现在支持对以下存储系统使用访问角色：

* Google Cloud NetApp卷


link:https://docs.netapp.com/us-en/bluexp-admin/reference-iam-predefined-roles.html["了解有关使用访问角色的更多信息。"]



=== 2025年7月14日



==== 连接器3.9.54

此版本的BlueXP Connector 包括安全性改进、错误修复以及以下新功能：

* 支持专用于支持Cloud Volumes ONTAP服务的连接器的透明代理。 link:https://docs.netapp.com/us-en/bluexp-setup-admin/task-configuring-proxy.html["了解有关配置透明代理的更多信息。"]
* 当连接器部署在 Google Cloud 环境中时，能够使用网络标签来帮助路由连接器流量。
* 用于连接器健康监控的附加产品内通知，包括 CPU 和 RAM 使用情况。


目前、3.9.54版本可用于标准模式和受限模式。



==== BlueXP  身份和访问管理(IAM)

BlueXP中的身份和访问管理现在提供以下功能：

* 支持私有模式下的 IAM，允许您管理BlueXP服务和应用程序的用户访问和权限。
* 简化身份联合的管理，包括更轻松的导航、更清晰的联合连接配置选项以及更好的现有联合的可见性。
* 访问BlueXP backup and recovery、 BlueXP disaster recovery和联合管理的角色。




===== 支持私有模式下的 IAM

BlueXP现已支持私有模式下的 IAM，让您能够管理BlueXP服务和应用程序的用户访问和权限。此项增强功能使私有模式客户能够利用基于角色的访问控制 (RBAC) 来提高安全性和合规性。

link:https://docs.netapp.com/us-en/bluexp-setup-admin/whats-new.html#iam["了解有关BlueXP中的 IAM 的更多信息。"]



===== 简化身份联合管理

BlueXP现在提供更直观的身份联合管理界面。这包括更便捷的导航、更清晰的联合连接配置选项，以及更强大的现有联合可见性。

通过身份联合启用单点登录 (SSO)，用户可以使用其公司凭证登录BlueXP 。这提高了安全性，减少了密码使用量，并简化了用户入职流程。

系统将提示您将所有现有的联合连接导入新界面，以获取新的管理功能。这样，您无需重新创建联合连接即可充分利用最新的增强功能。 link:https://docs.netapp.com/us-en/bluexp-setup-admin/task-federation-import.html["了解有关将现有联合连接导入BlueXP 的更多信息。"]

改进的联合管理允许您：

* 将多个已验证的域添加到联合连接，允许您将多个域与同一个身份提供商 (IdP) 一起使用。
* 在需要时禁用或删除联合连接，让您控制用户访问和安全。
* 使用 IAM 角色控制对联合管理的访问。


link:https://docs.netapp.com/us-en/bluexp-setup-admin/concept-federation.html["了解有关BlueXP中的身份联合的更多信息。"]



===== BlueXP backup and recovery、 BlueXP disaster recovery和联合管理的新访问角色

BlueXP现在支持使用 IAM 角色实现以下功能和数据服务：

* BlueXP备份和恢复
* BlueXP灾难恢复
* 联邦


link:https://docs.netapp.com/us-en/bluexp-admin/reference-iam-predefined-roles.html["了解有关使用访问角色的更多信息。"]



=== 2025年6月9日



==== 连接器3.9.53

BlueXP Connector 的此版本包括安全改进和错误修复。

3.9.53版本适用于标准模式和受限模式。



==== 磁盘空间使用情况警报

通知中心现在包含连接器上磁盘空间使用情况的警报。 link:https://docs.netapp.com/us-en/bluexp-setup-admin/task-maintain-connectors.html#monitor-disk-space["了解更多信息。"^]



==== 审计改进

时间线现在包含用户的登录和注销事件。您可以查看登录活动的时间，这有助于审计和安全监控。具有组织管理员角色的 API 用户可以通过添加以下信息来查看已登录用户的电子邮件地址：  `includeUserData=true``参数如下：  `/audit/<account_id>?includeUserData=true` 。



==== BlueXP 中提供 Keystone 订阅管理

您可以从 BlueXP 管理您的 NetApp Keystone 订阅。

link:https://docs.netapp.com/us-en/keystone-staas/index.html["了解 BlueXP 中的 Keystone 订阅管理。"^]



==== BlueXP  身份和访问管理(IAM)



===== 多因素身份验证（ MFA ）

非联合用户可以为其BlueXP帐户启用 MFA 以提高安全性。管理员可以管理 MFA 设置，包括根据需要为用户重置或禁用 MFA。这仅在标准模式下受支持。

link:https://docs.netapp.com/us-en/bluexp-setup-admin/task-user-settings.html#task-user-mfa["了解如何为自己设置多重身份验证。"^] link:https://docs.netapp.com/us-en/bluexp-setup-admin/task-iam-manage-members-permissions.html#manage-mfa["了解如何为用户管理多重身份验证。"^]



==== 工作负载

您现在可以从 BlueXP 中的凭证页面查看和删除 Amazon FSx for NetApp ONTAP 凭证。



=== 2025年5月29日



==== 专用模式版本(3.9.52)

现在、可从下载新的专用模式版本 https://mysupport.netapp.com/site/downloads["NetApp 支持站点"^]

3.9.52版本包括对以下BlueXP  组件和服务的更新。

[cols="3*"]
|===
| 组件或服务 | 此版本包含的版本 | 自上一个专用模式版本以来的更改 


| 连接器 | 3.9.52 3.9.51 | 转到 https://docs.netapp.com/us-en/bluexp-setup-admin/whats-new.html#connector-3-9-50["BlueXP  连接器页面中的新增功能"]、并参阅3.9.52和3.9.50中包含的更改。 


| 备份和恢复 | 2025年5月12日 | 前往 https://docs.netapp.com/us-en/bluexp-backup-recovery/whats-new.html["BlueXP  备份和恢复页面中的新增功能"^]并参考 2025 年 5 月版本中包含的更改。 


| 分类 | 2025 年 5 月 12 日（版本 1.43） | 转到 https://docs.netapp.com/us-en/bluexp-classification/whats-new.html["BlueXP  分类页面中的新增功能"^]、并参阅1.38 1.371.41版本中包含的更改。 
|===
有关专用模式的更多详细信息、包括如何升级、请参见以下内容：

* https://docs.netapp.com/us-en/bluexp-setup-admin/concept-modes.html["了解私有模式"]
* https://docs.netapp.com/us-en/bluexp-setup-admin/task-quick-start-private-mode.html["了解如何在私有模式下开始使用BlueXP"]
* https://docs.netapp.com/us-en/bluexp-setup-admin/task-upgrade-connector.html["了解如何在使用私有模式时升级连接器"]




== 警报



=== 2024年10月7日



==== BlueXP  警报列表页面

您可以快速识别容量低或性能低的ONTAP集群、评估可用性范围并识别安全风险。您可以查看与容量、性能、保护、可用性、安全性和配置相关的警报。



==== 警报详细信息

您可以深入了解警报详细信息并查找建议。



==== 查看链接到ONTAP系统管理器的集群详细信息

通过BlueXP  警报、您可以查看与ONTAP存储环境关联的警报、并深入查看链接到ONTAP系统管理器的详细信息。

https://docs.netapp.com/us-en/bluexp-alerts/concept-alerts.html["了解BlueXP  警报"](英文)



== 适用于 ONTAP 的 Amazon FSX



=== 2025年7月14日



==== 支持在两个 FSx for ONTAP 文件系统之间复制数据

现在可以通过 BlueXP 控制台在两个 FSx for ONTAP 文件系统之间进行数据复制。

link:https://docs.netapp.com/us-en/bluexp-fsx-ontap/use/task-manage-working-environment.html#replicate-data["复制数据"]



=== 2025年6月29日



==== 凭证更新

为 FSx for ONTAP 文件系统设置凭据和权限后，您将被重定向到 BlueXP 凭据页面。在此页面，您可以重命名或删除 FSx for ONTAP 凭据。

link:https://docs.netapp.com/us-en/bluexp-fsx-ontap/requirements/task-setting-up-permissions-fsx.html["设置 FSx for ONTAP 文件系统的权限"]



=== 2025年5月4日



==== 跟踪器响应支持

Tracker现在提供API响应、以便您可以查看与任务相关的REST API输出。



==== 支持对AWS专有信息管理器进行链接身份验证

现在、您可以选择使用AWS机密管理器中的密钥对链接进行身份验证、这样就不必使用存储在BlueXP  工作负载中的凭据。

link:https://docs.netapp.com/us-en/workload-fsx-ontap/create-link.html["使用Lamba链接连接到FSx for ONTAP文件系统"]



==== 为FSx for ONTAP文件系统实施最佳实践

BlueXP  工作负载提供了一个信息板、您可以在其中查看文件系统配置的架构良好状态。您可以利用此分析为FSx for ONTAP文件系统实施最佳实践。文件系统配置分析包括以下配置：SSD容量阈值、计划的本地快照、计划的ONTAP备份FSx、数据分层和远程数据复制。

* link:https://docs.netapp.com/us-en/workload-fsx-ontap/configuration-analysis.html["了解对文件系统配置进行精心设计的分析"]
* link:https://review.docs.netapp.com/us-en/workload-fsx-ontap_well-architected/improve-configurations.html["为文件系统实施最佳实践"]




==== 针对文件系统问题设计合理的通知

现在、在BlueXP  控制台中、对于架构良好的文件系统、FSx for ONTAP文件系统会在"画布"中显示一条通知、指示何时文件系统存在问题需要修复。



==== 更新了权限术语

工作负载工厂用户界面和文档现在使用“只读”来指代读取权限，使用“读/写”来指代自动化权限。



== Amazon S3存储



=== 2023年3月5日



==== 能够从BlueXP添加新存储分段

您可以在BlueXP Canvas上查看Amazon S3存储分段已有一段时间了。现在、您可以直接从BlueXP  添加新存储分段并更改现有存储分段的属性。 https://docs.netapp.com/us-en/bluexp-s3-storage/task-add-s3-bucket.html["了解如何添加新的Amazon S3存储分段"](英文)。



== Azure Blb存储



=== 2023年6月5日



==== 能够从BlueXP添加新存储帐户

您已有一段时间可以在BlueXP Canvs上查看Azure Blb Storage了。现在、您可以直接从BlueXP  添加新存储帐户并更改现有存储帐户的属性。 https://docs.netapp.com/us-en/bluexp-blob-storage/task-add-blob-storage.html["了解如何添加新的Azure Blb存储帐户"](英文)。



== Azure NetApp Files



=== 2025年1月13日



==== BlueXP  现在支持网络功能

现在、从BlueXP  在Azure NetApp Files中配置卷时、您可以指示网络功能。这与本机Azure NetApp Files中提供的功能一致。



=== 2024年6月12日



==== 需要新权限

现在、要从BlueXP管理Azure NetApp Files卷、需要以下权限：

Microsoft.Network/virtualNetworks/subnets/read

读取虚拟网络子网需要此权限。

如果您当前正在从BlueXP管理Azure NetApp Files、则需要将此权限添加到与先前创建的Microsoft Entra应用程序关联的自定义角色。

https://docs.netapp.com/us-en/bluexp-azure-netapp-files/task-set-up-azure-ad.html["了解如何设置Microsoft Entra应用程序和查看自定义角色权限"](英文)



=== 2024年4月22日



==== 不再支持卷模板

您无法再使用模板创建卷。此操作与BlueXP修复服务关联、此服务不再可用。



== 备份和恢复



=== 2025年7月14日

此BlueXP  备份和恢复版本包含以下更新。



==== 增强型ONTAP卷仪表板

2025 年 4 月，我们推出了增强型ONTAP卷仪表板的预览版，它速度更快、更高效。

此仪表板旨在帮助企业客户处理大量工作负载。即使对于拥有 20,000 个卷的客户，新仪表板也能在 10 秒内加载完成。

预览版成功上线，并获得了众多预览版用户的积极反馈，我们现已将其设为所有客户的默认体验。准备好迎接极速仪表板吧！

有关详细信息，请参见 link:br-use-dashboard.html["在仪表板中查看保护健康状况"]。



==== Microsoft SQL Server 工作负载支持作为公共技术预览

此版本的BlueXP backup and recovery提供了更新的用户界面，使您能够使用BlueXP backup and recovery服务中熟悉的 3-2-1 保护策略来管理 Microsoft SQL Server 工作负载。使用此新版本，您可以将这些工作负载备份到主存储，复制到辅助存储，然后备份到云对象存储。

您可以通过完成此步骤注册预览 https://forms.office.com/pages/responsepage.aspx?id=oBEJS5uSFUeUS8A3RRZbOojtBW63mDRDv3ZK50MaTlJUNjdENllaVTRTVFJGSDQ2MFJIREcxN0EwQi4u&route=shorturl["预览注册表"^] 。


NOTE: 本文档是关于保护微软 SQL SERVER 工作负载的，作为技术预览提供。对于此预览版产品、NetApp保留在正式发布之前修改产品详细信息、内容和时间表的权利。

此版本的BlueXP backup and recovery包括以下更新：

* *3-2-1 备份功能*：此版本集成了SnapCenter功能，使您能够通过BlueXP backup and recovery用户界面使用 3-2-1 数据保护策略来管理和保护您的SnapCenter资源。
* *从SnapCenter导入*：您可以将SnapCenter备份数据和策略导入BlueXP backup and recovery。
* *重新设计的用户界面*为管理备份和恢复任务提供了更直观的体验。
* *备份目标*：您可以在 Amazon Web Services (AWS)、Microsoft Azure Blob Storage、 StorageGRID和ONTAP S3 环境中添加存储桶，以用作 Microsoft SQL Server 工作负载的备份目标。
* *工作负载支持*：此版本支持您备份、还原、验证和克隆 Microsoft SQL Server 数据库和可用性组。（未来版本将添加对其他工作负载的支持。）
* *灵活的恢复选项*：此版本使您能够在发生损坏或意外数据丢失的情况下将数据库恢复到原始位置和备用位置。
* *即时生产副本*：在几分钟内（而不是几小时或几天）生成用于开发、测试或分析的节省空间的生产副本。
* 此版本包括创建详细报告的功能。


有关保护 Microsoft SQL Server 工作负载的详细信息，请参阅link:br-use-mssql-protect-overview.html["保护 Microsoft SQL Server 工作负载概述"] 。



=== 2025 年 6 月 9 日

此BlueXP  备份和恢复版本包含以下更新。



==== 索引目录支持更新

2025 年 2 月，我们推出了更新的索引功能（索引目录 v2），您可以在“搜索和还原”数据还原方法中使用此功能。上一版本显著提升了本地环境中的数据索引性能。在此版本中，索引目录现已可在 Amazon Web Services、Microsoft Azure 和 Google Cloud Platform (GCP) 环境中使用。

如果您是新客户，所有新环境均默认启用索引目录 v2。如果您是现有客户，您可以重新索引您的环境以利用索引目录 v2。

.如何启用索引编制？
在使用搜索和还原方法还原数据之前、您需要在计划从中还原卷或文件的每个源工作环境上启用"索引编制"。执行搜索和恢复时，选择“*启用索引*”选项。

索引目录可以跟踪每个卷和备份文件，使您的搜索快速而高效。

有关详细信息，请参阅 https://docs.netapp.com/us-en/bluexp-backup-recovery/prev-ontap-restore.html["启用搜索和还原索引"]。



==== Azure 专用链接终结点和服务终结点

通常， BlueXP backup and recovery会与云提供商建立一个私有端点来处理保护任务。此版本引入了一项可选设置，可让您启用或禁用 BlueXP 备份和恢复自动创建私有端点的功能。如果您希望更好地控制私有端点的创建过程，这项设置可能会对您有所帮助。

您可以在启用保护或开始恢复过程时启用或禁用此选项。

如果禁用此设置，则必须手动创建专用端点，以确保 BlueXP 备份和恢复功能正常运行。如果没有正确的连接，您可能无法成功执行备份和恢复任务。



==== ONTAP S3 上支持 SnapMirror 到云重新同步

上一版本引入了对 SnapMirror 到云重新同步 (SM-C Resync) 的支持。该功能简化了 NetApp 环境中卷迁移期间的数据保护。此版本增加了对 ONTAP S3 以及其他兼容 S3 的提供商（例如 Wasabi 和 MinIO）上的 SM-C Resync 的支持。



==== 为 StorageGRID 带来您自己的存储桶

当您在对象存储中为工作环境创建备份文件时，BlueXP 备份和恢复功能会默认在您配置的对象存储帐户中为备份文件创建容器（存储桶或存储帐户）。之前，您可以覆盖此设置，并为 Amazon S3、Azure Blob Storage 和 Google Cloud Storage 指定您自己的容器。在此版本中，您现在可以自带 StorageGRID 对象存储容器。

请参阅。 https://docs.netapp.com/us-en/bluexp-backup-recovery/prev-ontap-protect-journey.html["创建您自己的对象存储容器"]



=== 2025年5月13日

此BlueXP  备份和恢复版本包含以下更新。



==== SnapMirror到云重新同步以进行卷迁移

SnapMirror到云重新同步功能可简化NetApp环境中卷迁移期间的数据保护和连续性。使用SnapMirror逻辑复制(LRSE)将卷迁移到内部NetApp部署或Cloud Volumes ONTAP或Cloud Volumes Service等基于云的解决方案时、SnapMirror到云重新同步可确保现有云备份保持完好且正常运行。

此功能无需执行耗时且资源密集型的重新基线操作、从而可以在迁移后继续执行备份操作。此功能在工作负载迁移方案中非常有用、可同时支持FlexVol和FlexGroup、并可从ONTAP 9.161版开始使用。

通过在不同环境之间保持备份连续性、SnapMirror到云重新同步可提高运营效率、并降低混合云和多云数据管理的复杂性。

有关如何执行重新同步操作的详细信息，请参见 https://docs.netapp.com/us-en/bluexp-backup-recovery/prev-ontap-migrate-resync.html["使用SnapMirror迁移卷到云重新同步"]。



==== 支持第三方MinIO对象存储(预览)

BlueXP  备份和恢复现在将其支持扩展到第三方对象存储、并主要侧重于MinIO。通过这一新的预览功能、您可以利用任何与S3兼容的对象存储来满足备份和恢复需求。

在此预览版本中、我们希望确保在推出完整功能之前与第三方对象存储实现强大集成。我们鼓励您探索这项新功能、并提供反馈以帮助改进服务。


IMPORTANT: 此功能不应在生产环境中使用。

*预览模式限制*

在预览此功能时、存在一些限制：

* 不支持自带存储分段(BYOB)。
* 不支持在策略中启用DataLock。
* 不支持在策略中启用归位模式。
* 仅支持内部ONTAP环境。
* 不支持MetroCluster。
* 不支持用于启用存储分段级别加密的选项。


* 入门 *

要开始使用此预览功能、您必须在BlueXP  连接器上启用一个标志。然后、您可以通过在备份部分中选择*第三方兼容*对象存储、在保护工作流中输入您的Minio第三方对象存储的连接详细信息。



== 分类



=== 2025年7月14日



==== 1.45 版

此BlueXP classification版本包括优化资源利用率的代码更改以及：

.改进了添加文件共享进行扫描的工作流程
将文件共享添加到文件共享组的工作流程已简化。该流程现在还根据身份验证类型（Kerberos 或 NTLM）区分 CIFS 协议支持。

有关详细信息，请参见 link:https://docs.netapp.com/us-en/bluexp-classification/task-scanning-file-shares.html["扫描文件共享"]。

.增强文件所有者信息
现在，您可以查看“调查”选项卡中捕获文件的文件所有者的更多信息。在“调查”选项卡中查看文件的元数据时，找到文件所有者，然后选择“查看详细信息”以查看用户名、电子邮件和 SAM 帐户名。您还可以查看此用户拥有的其他项目。此功能仅适用于具有 Active Directory 的工作环境。

有关详细信息，请参见 link:https://docs.netapp.com/us-en/bluexp-classification/task-investigate-data.html["调查存储在组织中的数据"]。



=== 2025年6月10日



==== 1.44 版

此BlueXP  分类版本包括：

.改进了治理仪表板的更新时间
治理仪表板各个组件的更新时间已得到改进。下表显示了每个组件的更新频率。

[cols="1,1"]
|===
| 组件 | 更新时间 


| 数据使用期限 | 24 小时 


| 类别 | 24 小时 


| 数据概述 | 5 分钟 


| 重复文件 | 2 小时 


| 文件类型 | 24 小时 


| 非业务数据 | 2 小时 


| 打开权限 | 24 小时 


| 保存的搜索 | 2 小时 


| 敏感数据和广泛权限 | 24 小时 


| 数据大小 | 24 小时 


| 陈旧数据 | 2 小时 


| 按敏感度级别划分的顶级数据存储库 | 2 小时 
|===
您可以查看上次更新时间，并手动更新“重复文件”、“非业务数据”、“已保存的搜索”、“过时数据”和“按敏感度级别排名靠前的数据存储库”组件。有关“治理”仪表板的更多信息，请参阅link:https://docs.netapp.com/us-en/bluexp-classification/task-controlling-governance-data.html["查看有关组织中存储的数据的监管详细信息"] 。

.性能和安全改进
我们已经进行了增强以提高 BlueXP 分类的性能、内存消耗和安全性。

.错误修复
Redis 已升级，以提高 BlueXP 分类的可靠性。BlueXP分类现在使用 Elasticsearch 来提高扫描期间文件数量报告的准确性。



=== 2025年5月12日



==== 1.43 版

此BlueXP  分类版本包括：

.确定分类扫描的优先级
除了仅映射扫描之外、BlueXP  分类还支持划分地图和分类扫描的优先级、使您能够选择首先完成哪些扫描。在扫描开始期间和之前、支持对映射和分类扫描进行优先排序。如果您选择在扫描过程中确定扫描优先级、则映射扫描和分类扫描都将确定优先级。

有关详细信息，请参见 link:https://docs.netapp.com/us-en/bluexp-classification/task-managing-repo-scanning.html#prioritize-scans["确定扫描优先级"]。

.支持加拿大个人身份信息(个人身份信息、个人身份信息)数据类别
BlueXP  分类扫描可识别加拿大的可识别身份信息数据类别。这些类别包括加拿大所有省份和地区的银行信息、护照号码、社会保险号码、驾驶执照号码和健康卡号码。

有关详细信息，请参见 link:https://docs.netapp.com/us-en/bluexp-classification/reference-private-data-categories.html#types-of-personal-data["个人数据类别"]。

.自定义分类(预览)
BlueXP  分类支持对映射和分类扫描进行自定义分类。通过自定义分类、您可以定制BlueXP  扫描、以便使用正则表达式捕获特定于您的组织的数据。此功能当前处于预览状态。

有关详细信息，请参见 link:https://docs.netapp.com/us-en/bluexp-classification/task-custom-classification.html["添加自定义分类"]。

.已保存搜索选项卡
**策略**选项卡已重命名link:https://docs.netapp.com/us-en/bluexp-classification/task-using-policies.html["**保存的搜索**"]。功能没有改变。

.将扫描事件发送到BlueXP  时间线
BlueXP  分类支持将分类事件(扫描启动和结束时)发送到link:https://docs.netapp.com/us-en/bluexp-setup-admin/task-monitor-cm-operations.html#audit-user-activity-from-the-bluexp-timeline["BlueXP  时间表"^]。

.安全更新
* Keras软件包已更新、可缓解漏洞(BDSA-2025-0107和BDSA-2025-1984)。
* 已更新Docker容器配置。容器无法再访问主机的网络接口来创建原始网络数据包。通过减少不必要的访问、此更新可缓解潜在的安全风险。


.性能增强
已实施代码增强功能、以减少RAM使用量并提高BlueXP  分类的整体性能。

.错误修复
已修复导致StorageGRID扫描失败、无法加载调查页面筛选器选项以及无法下载数据发现评估进行高容量评估的错误。



=== 2025年4月14日



==== 1.42 版

此BlueXP  分类版本包括：

.针对工作环境进行批量扫描
BlueXP  分类支持对工作环境执行批量操作。您可以选择启用映射扫描、启用映射和分类扫描、禁用扫描或跨工作环境中的卷创建自定义配置。如果您为单个卷进行选择、则会覆盖批量选择。要执行批量操作，请导航到**配置**页并进行选择。

.在本地下载调查报告
BlueXP  分类支持在本地下载数据调查报告以在浏览器中查看。如果您选择本地选项、则数据调查仅以CSV格式提供、并且仅显示前10、000行数据。

有关详细信息，请参见 link:https://docs.netapp.com/us-en/bluexp-classification/task-investigate-data.html#create-the-data-investigation-report["根据BlueXP  分类调查存储在您的组织中的数据"]。



=== 2025年3月10日



==== 1.41 版

此BlueXP  分类版本包括一些常规改进和错误修复。它还包括：

.扫描状态
BlueXP  分类可跟踪卷上_initial-_映射和分类扫描的实时进度。单独的渐进式条可跟踪映射和分类扫描、显示扫描总文件的百分比。您也可以将鼠标悬停在进度条上以查看扫描的文件数和总文件数。跟踪扫描状态可更深入地了解扫描进度、使您能够更好地规划扫描并了解资源分配。

要查看扫描的状态，请导航到BlueXP  分类中的**配置**，然后选择**工作环境配置**。每个卷的进度将以行显示。



=== 2025年2月19日



==== 1.40 版

此BlueXP  分类版本包含以下更新。

.支持RHEL 9.5
除了先前支持的版本之外、此版本还支持Red Hat Enterprise Linux v9.5。这适用于BlueXP  分类的任何手动内部安装、包括非公开站点部署。

以下操作系统要求使用Podman容器引擎、并要求使用BlueXP  分类版本1.3或更高版本：Red Hat Enterprise Linux版本8.8、8.10、9.0、9.1、9.2、9.3、9.4和9.5。

.确定仅映射扫描的优先级
执行仅映射扫描时、您可以确定最重要扫描的优先级。如果您有许多工作环境、并希望确保首先完成高优先级扫描、则此功能会很有帮助。

默认情况下、扫描会根据启动顺序进行排队。通过确定扫描优先级的功能、您可以将扫描移动到队列的前端。可以确定多个扫描的优先级。优先级按先入先出的顺序指定、这意味着您优先处理的第一个扫描将移至队列的前端；您优先处理的第二个扫描将成为队列中的第二个扫描、依此类推。

优先权是一次性授予的。按默认顺序自动重新选择映射数据。

优先级限制为link:https://docs.netapp.com/us-en/bluexp-classification/concept-cloud-compliance.html["仅映射扫描"^]；它不适用于地图扫描和分类扫描。

有关详细信息，请参见 link:https://docs.netapp.com/us-en/bluexp-classification/task-managing-repo-scanning.html#prioritize-scans["确定扫描优先级"^]。

.重试所有扫描
BlueXP  分类支持批量重试所有失败的扫描。

可以使用**重试全部**功能在批处理操作中重新尝试扫描。如果分类扫描因网络中断等临时问题而失败、您可以使用一个按钮同时重试所有扫描、而不是逐个重试。可以根据需要多次重试扫描。

重试所有扫描：

. 从BlueXP  分类菜单中，选择*Configuration*。
. 要重试所有失败的扫描，请选择*重试所有扫描*。


.提高了分类模型的准确性
的机器学习模型准确性link:https://docs.netapp.com/us-en/bluexp-classification/reference-private-data-categories.html#types-of-sensitive-personal-datapredefined-categories["预定义的类别"]提高了11%。



=== 2025年1月22日



==== 1.39 版

此BlueXP  分类版本更新了数据调查报告的导出流程。此导出更新适用于对数据执行其他分析、为数据创建其他可视化效果或与他人共享数据调查结果。

以前、数据调查报告导出限制为10、000行。此版本已删除限制、您可以导出所有数据。通过此更改、您可以从数据调查报告导出更多数据、从而提高数据分析的灵活性。

您可以选择工作环境、卷、目标文件夹以及JSON或CSV格式。导出的文件名包含一个时间戳、可帮助您确定数据的导出时间。

支持的工作环境包括：

* Cloud Volumes ONTAP
* 适用于 ONTAP 的 FSX
* ONTAP
* 共享组


从数据调查报告导出数据时存在以下限制：

* 要下载的最大记录数为5亿。每种类型(文件、目录和表)
* 100万条记录预计需要大约35分钟才能导出。


有关数据调查和报告的详细信息，请参见 https://docs.netapp.com/us-en/bluexp-classification/task-investigate-data.html["调查存储在组织中的数据"]。



=== 2024年12月16日



==== 1.38 版

此BlueXP  分类版本包括一些常规改进和错误修复。



== Cloud Volumes ONTAP



=== 2025年7月14日



==== 支持透明代理

除了现有的显式代理连接之外， BlueXP现在还支持透明代理服务器。创建或修改BlueXP连接器时，您可以配置透明代理服务器，以安全地管理往返于Cloud Volumes ONTAP 的网络流量。

有关在Cloud Volumes ONTAP中使用代理服务器的更多信息，请参阅：

* https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/reference-networking-aws.html#network-configurations-to-support-connector-proxy-servers["用于支持 AWS 中的连接器代理的网络配置"^]
* https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/azure/reference-networking-azure.html#network-configurations-to-support-connector["用于支持 Azure 中的连接器代理的网络配置"^]
* https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/reference-networking-gcp.html#network-configurations-to-support-connector-proxy["用于支持 Google Cloud 中的连接器代理的网络配置"^]




==== Azure 中的Cloud Volumes ONTAP支持新的 VM 类型

从Cloud Volumes ONTAP 9.13.1 开始，L8s_v3 作为 Azure 单个和多个可用区域中的 VM 类型受到支持，适用于新的和现有的高可用性 (HA) 对部署。

有关详细信息，请参阅 https://docs.netapp.com/us-en/cloud-volumes-ontap-relnotes/reference-configs-azure.html["Azure 中支持的配置"^]。



=== 2025年5月29日



==== 为Cloud Volumes ONTAP 9.15.1启用了专用模式部署

现在、您可以在AWS、Azure和Google Cloud中以私有模式部署Cloud Volumes ONTAP 9.15.1。Cloud Volumes ONTAP 9.15.1的单节点和高可用性(HA)部署均启用了专用模式。

有关私有模式部署的详细信息，请参见https://docs.netapp.com/us-en/bluexp-setup-admin/concept-modes.html#restricted-mode["了解BlueXP部署模式"^]。



=== 2025年5月12日



==== 发现通过BlueXP  中的Azure Marketplace进行的部署

BlueXP  现在可以直接通过Azure市场发现部署的Cloud Volumes ONTAP系统。这意味着、您现在可以像添加任何其他Cloud Volumes ONTAP系统一样、在BlueXP  中将这些系统作为工作环境进行添加和管理。

https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/task-deploy-cvo-azure-mktplc.html["从Azure Marketplace部署Cloud Volumes ONTAP"^]



==== 能够为Azure租户分层数据

现在、在Cloud Volumes ONTAP工作环境由一个租户创建而BlueXP  连接器由另一个租户创建的情况下、您可以为Azure租户启用分层。通过使用此功能、您可以使用同一个Connector为多个Azure租户分层数据。

https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/task-tiering.html#requirements-to-tier-data-for-an-azure-tenant["为Azure租户分层数据的要求"^]



== 适用于 Google Cloud 的 Cloud Volumes Service



=== 2020年9月9日



==== 支持适用于 Google Cloud 的 Cloud Volumes Service

现在、您可以直接从BlueXP管理适用于Google Cloud的Cloud Volumes Service ：

* 设置和创建工作环境
* 为 Linux 和 UNIX 客户端创建和管理 NFSv3 和 NFSv4.1 卷
* 为 Windows 客户端创建和管理 SMB 3.x 卷
* 创建，删除和还原卷快照




== 复制和同步



=== 2025年2月2日



==== 为数据代理提供了新的操作系统支持

现在、运行Red Hat Enterprise 9.4、Ubuntu 23.04和Ubuntu 24.04的主机支持数据代理。

https://docs.netapp.com/us-en/bluexp-copy-sync/task-installing-linux.html#linux-host-requirements["查看Linux主机要求"](英文)



=== 2024年10月27日



==== 错误修复

我们更新了BlueXP复制和同步服务以及数据代理以修复一些错误。新的数据代理版本为1.0.56。



=== 2024年9月16日



==== 错误修复

我们更新了BlueXP复制和同步服务以及数据代理以修复一些错误。新的数据代理版本为1.0.55。



== 数字顾问



=== 2025年7月9日



==== Upgrade Advisor

* 升级顾问计划新增了多格式下载选项，以简化ONTAP升级规划并解决潜在的阻碍或警告。现在，您可以下载 Excel、PDF 和 JSON 格式的升级顾问计划。
* 在升级顾问计划的 Excel 格式中，进行了以下增强：
+
** 您可以查看在集群上执行的预检查，并使用“通过”、“失败”或“跳过”等指示标记结果。这可确保集群处于最佳状态，以完成ONTAP升级。
** 您可以查看适用于集群的推荐最新固件更新，以及ONTAP目标版本附带的版本。
** 新增了一个选项卡，用于检查 SAN 集群的互操作性。该选项卡可显示所选目标ONTAP版本支持的主机操作系统版本。






=== 2025年5月8日



==== AutoSupport小工具

AutoSupport小工具已进行了增强、其中包含一个弹出窗口、可提供有关已停止发送AutoSupport数据的系统的详细信息。启用AutoSupport可降低停机风险、并支持主动式系统运行状况管理。



==== 支持合同报告

支持合同报告已得到增强、可包括新的asp/LSG标志字段。使用此字段可以筛选和标识授权支持合作伙伴(也称为生命周期服务认证)所涵盖的系统。



==== Sustainability信息板

现在、您可以使用Sustainability演示文稿中的链接启动Sustainability信息板。



=== 2025年3月5日



==== Upgrade Advisor

* 现在、您可以使用磁盘认证包(DQP)根据预定义的运行状况和性能标准自动更新磁盘控制器和存储设备固件。这样可以减少潜在故障并提高整体系统可靠性。
* 引入了时区数据库(DB)、用于自动保持系统与最新时区定义保持一致。这样可以确保即使时区规则发生更改、依赖时间的操作也能顺利进行。




== 数字电子钱包



=== 2025年3月10日



==== 删除订阅的功能

如果您取消订阅、现在可以从电子钱包中删除订阅。



==== 查看Marketplace订阅的已用容量

现在、在查看PAYGO订阅时、您可以查看此订阅的已用容量。



=== 2025年2月10日

BlueXP  数字钱包经过重新设计、易于使用、现在可提供额外的订阅和许可证管理。



==== 新增了"概述"信息板

数字钱包主页提供了一个更新的NetApp许可证和Marketplace订阅信息板、可以深入查看特定服务、许可证类型和所需操作。



==== 配置凭据订阅

现在、您可以通过BlueXP  数字钱包为提供商凭据配置订阅。通常、您在首次订阅Marketplace订阅或年度合同时会执行此操作。以前只能在"凭据"页面上更改订阅的凭据。



==== 将订阅与组织相关联

现在、您可以直接从数字钱包更新订阅关联到的组织。



==== 管理Cloud Volume ONTAP许可证

现在，您可以通过主页或*直接许可证*选项卡管理Cloud Volumes ONTAP许可证。使用*商城订阅*选项卡查看您的订阅信息。



=== 2024年3月5日



==== BlueXP灾难恢复

BlueXP数字钱包现在可用于管理BlueXP灾难恢复的许可证。您可以添加许可证、更新许可证以及查看有关已许可容量的详细信息。

https://docs.netapp.com/us-en/bluexp-digital-wallet/task-manage-data-services-licenses.html["了解如何管理BlueXP数据服务的许可证"]



=== 2023年7月30日



==== 使用情况报告增强功能

Cloud Volumes ONTAP使用情况报告现已有多项改进：

* 此时、TiB单元将包含在列名称中。
* 现在、包含了一个用于序列号的新_node (s)_字段。
* 现在、Storage VM使用情况报告下会包含一个新的_Workload Type_列。
* 现在、工作环境名称会包含在Storage VM和卷使用情况报告中。
* 卷类型_file_现在标记为_Primary (Read/Write)_。
* 卷类型_Secondary (DP)_现在标记为_Secondary (DP)_。


有关使用情况报告的详细信息、请参见 https://docs.netapp.com/us-en/bluexp-digital-wallet/task-manage-capacity-licenses.html#download-usage-reports["下载使用情况报告"]。



== 灾难恢复



=== 2025年7月14日

4.2.5版



==== BlueXP disaster recovery中的用户角色

BlueXP disaster recovery现在采用角色来管理每个用户对特定功能和操作的访问权限。

该服务使用特定于BlueXP disaster recovery的以下角色。

* *灾难恢复管理员*：在BlueXP disaster recovery中执行任何操作。
* *灾难恢复故障转移管理*：在BlueXP disaster recovery中执行故障转移和迁移操作。
* *灾难恢复应用程序管理员*：创建和修改复制计划并启动测试故障转移。
* *灾难恢复查看器*：查看BlueXP disaster recovery中的信息，但不能执行任何操作。


如果您单击BlueXP disaster recovery服务并首次对其进行配置，则必须具有 *SnapCenterAdmin* 权限或具有 *Organization Admin* 角色。

有关详细信息，请参见  https://docs.netapp.com/us-en/bluexp-disaster-recovery/reference/dr-reference-roles.html["BlueXP disaster recovery中的用户角色和权限"]。

https://docs.netapp.com/us-en/bluexp-setup-admin/reference-iam-predefined-roles.html["了解所有服务的 BlueXP 访问角色"^](英文)



==== BlueXP disaster recovery中的其他更新

* 增强网络发现
* 可扩展性改进：
+
** 过滤所需的元数据而不是所有细节
** 发现改进，可以更快地检索和更新虚拟机资源
** 数据检索和数据更新的内存优化和性能优化
** vCenter SDK 客户端创建和池管理改进


* 下次计划或手动发现时的陈旧数据管理：
+
** 当在 vCenter 中删除虚拟机时， BlueXP disaster recovery现在会自动将其从复制计划中删除。
** 当 vCenter 中删除数据存储区或网络时， BlueXP disaster recovery现在会将其从复制计划和资源组中删除。
** 当在 vCenter 中删除集群、主机或数据中心时， BlueXP disaster recovery现在会将其从复制计划和资源组中删除。


* 现在，您可以在浏览器的隐身模式下访问 Swagger 文档。您可以在BlueXP disaster recovery中通过“设置”选项 > “API 文档”访问它，也可以在浏览器的隐身模式下直接通过以下 URL 访问它：  https://snapcenter.cloudmanager.cloud.netapp.com/api/api-doc/draas["Swagger 文档"^] 。
* 在某些情况下，故障回复操作完成后，iGroup 会被遗留。如果 iGroup 已过期，此更新会将其移除。
* 如果复制计划中使用了 NFS FQDN， BlueXP disaster recovery现在会将其解析为 IP 地址。如果灾难恢复站点无法解析 FQDN，则此更新非常有用。
* UI 对齐改进
* 成功发现后，记录捕获 vCenter 大小详细信息的日志改进




=== 2025年6月30日

版本4.2.4P2



==== 发现改进

此更新改进了发现过程，从而减少了发现所需的时间。



=== 2025年6月23日

版本4.2.4P1



==== 子网映射改进

本次更新增强了“添加和编辑子网映射”对话框，新增了搜索功能。现在，您可以通过输入搜索词快速查找特定子网，从而更轻松地管理子网映射。



=== 2025年6月9日

4.2.4版



==== Windows 本地管理员密码解决方案 (LAPS) 支持

Windows 本地管理员密码解决方案 (Windows LAPS) 是一项 Windows 功能，可自动管理和备份 Active Directory 上本地管理员帐户的密码。

现在，您可以通过提供域控制器详细信息来选择子网映射选项并检查 LAPS 选项。使用此选项，您无需为每个虚拟机提供密码。

有关详细信息，请参见 https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/drplan-create.html["创建复制计划"]。



== E系列系统



=== 2025年5月12日



==== 需要 BlueXP 访问角色

现在，您需要以下访问角色之一来查看、发现或管理 BlueXP 中的 E 系列：组织管理员、文件夹或项目管理员、存储管理员或系统健康专家。  https://docs.netapp.com/us-en/bluexp/reference-iam-predefined-roles.html["了解 BlueXP 访问角色。"^]



=== 2022年9月18日



==== 支持E系列

现在、您可以直接从BlueXP发现E系列系统。通过发现E系列系统、您可以全面了解混合多云中的数据。



== 经济效率



=== 2024年5月15日



==== 禁用的功能

BlueXP  的一些经济效益功能已暂时禁用：

* 技术更新
* 添加容量




=== 2024年3月14日



==== 技术更新选项

如果您已有资产、并且希望确定是否需要更新某项技术、则可以使用BlueXP经济高效技术更新选项。您可以查看当前工作负载的简短评估并获取建议、或者如果您在过去90天内将AutoSupport日志发送给NetApp、则该服务现在可以提供工作负载模拟、以查看工作负载在新硬件上的运行情况。

您还可以添加工作负载并从模拟中排除现有工作负载。

以前、您只能对资产进行评估、并确定是否建议进行技术更新。

此功能现在是左侧导航栏中技术更新选项的一部分。

了解有关的更多信息 https://docs.netapp.com/us-en/bluexp-economic-efficiency/use/tech-refresh.html["评估技术更新"]。



=== 2023年11月8日



==== 技术更新

此版本的BlueXP经济高效功能提供了一个新选项、可用于评估您的资产并确定是否建议进行技术更新。此服务包括左侧导航栏中的新技术更新选项、可用于评估当前工作负载和资产的新页面以及可为您提供建议的报告。



== 边缘缓存

BlueXP  边缘缓存服务已于2024年8月7日被删除。



== Google Cloud 存储



=== 2023年7月10日



==== 可以通过BlueXP添加新存储分段并管理现有存储分段

您可以在BlueXP Canvs上查看Google Cloud Storage存储分段已有很长一段时间了。现在、您可以直接从BlueXP  添加新存储分段并更改现有存储分段的属性。 https://docs.netapp.com/us-en/bluexp-google-cloud-storage/task-add-gcp-bucket.html["了解如何添加新的Google Cloud存储分段"](英文)。



== Keystone



=== 2025年6月19日



==== BlueXP 中的 Keystone 仪表板

您现在可以直接从 BlueXP 访问 Keystone 仪表板。此集成让您可以在一个位置监控、管理和跟踪所有 Keystone 订阅以及其他 NetApp 服务。

使用 BlueXP 中的 Keystone 仪表板，您可以：

* 在一个地方查看所有订阅详细信息、容量使用情况和资产。
* 轻松管理订阅并随着需求的变化请求更改。
* 随时了解有关您的存储环境的最新信息。


首先，转到 BlueXP 左侧导航菜单中的 *存储 > Keystone*。要了解更多信息，请参阅 link:https://docs.netapp.com/us-en/keystone-staas/integrations/dashboard-overview.html["Keystone信息板概述"]。



== Kubernetes

2024年8月7日、不再支持发现和管理Kubbernetes集群。



== 迁移报告

BlueXP  迁移报告服务已于2024年8月7日删除。



== 内部 ONTAP 集群



=== 2025年5月12日



==== 需要 BlueXP 访问角色

现在，您需要以下访问角色之一来查看、发现或管理本地 ONTAP 集群：组织管理员、文件夹或项目管理员、存储管理员或系统健康专家。 link:https://docs.netapp.com/us-en/bluexp/concept-iam-predefined-roles.html["了解 BlueXP 访问角色。"^]



=== 2024年11月26日



==== 支持使用专用模式的ASA R2系统

现在、在私有模式下使用BlueXP  时、您可以发现NetApp ASA R2系统。从BlueXP  的3.9.46专用模式版本开始、可提供此支持。

* https://docs.netapp.com/us-en/asa-r2/index.html["详细了解ASA R2系统"^]
* https://docs.netapp.com/us-en/bluexp-setup-admin/concept-modes.html["了解BlueXP部署模式"^]




=== 2024年10月7日



==== 支持ASA R2系统

现在、如果在标准模式或受限模式下使用BlueXP 、则可以在BlueXP  中发现NetApp ASA R2系统。发现NetApp ASA R2系统并打开工作环境后、您将直接转到System Manager。

ASA R2系统没有其他可用的管理选项。您不能使用标准视图、也不能启用BlueXP服务。

在专用模式下使用BlueXP  时、不支持发现ASA R2系统。

* https://docs.netapp.com/us-en/asa-r2/index.html["详细了解ASA R2系统"^]
* https://docs.netapp.com/us-en/bluexp-setup-admin/concept-modes.html["了解BlueXP部署模式"^]




== 运营故障恢复能力



=== 2023年4月2日



==== BlueXP  操作故障恢复能力服务

通过使用新的BlueXP操作故障恢复能力服务及其自动化IT操作风险修复建议、您可以在发生中断或故障之前实施建议的修复措施。

运营故障恢复能力是一项服务、可帮助您分析警报和事件、以保持服务和解决方案的运行状况、正常运行时间和性能。

link:https://docs.netapp.com/us-en/bluexp-operational-resiliency/get-started/intro.html["详细了解BlueXP操作故障恢复能力"]。



== 勒索软件保护



=== 2025年7月15日



==== SAN 工作负载支持

此版本包含对BlueXP ransomware protection中 SAN 工作负载的支持。现在，除了 NFS 和 CIFS 工作负载之外，您还可以保护 SAN 工作负载。

有关详细信息，请参阅 link:https://docs.netapp.com/us-en/bluexp-ransomware-protection/rp-start-prerequisites.html["BlueXP勒索软件保护前提条件"]。



==== 改进的工作负载保护

此版本改进了使用其他NetApp工具（例如SnapCenter或BlueXP backup and recovery）的快照和备份策略的工作负载的配置流程。在之前的版本中， BlueXP ransomware protection会发现其他工具的策略，因此您只能更改检测策略。在此版本中，您现在可以将快照和备份策略替换为BlueXP ransomware protection策略，也可以继续使用其他工具的策略。

有关详细信息，请参见 link:https://docs.netapp.com/us-en/bluexp-ransomware-protection/rp-use-protect.html["保护工作负载"]。



==== 电子邮件通知

如果BlueXP ransomware protection检测到可能的攻击， BlueXP通知中会出现通知，并且会向您配置的电子邮件地址发送电子邮件。

该电子邮件包含有关严重程度、受影响工作负载的信息，以及指向BlueXP ransomware protection“警报”选项卡中警报的链接。

如果您在BlueXP ransomware protection中配置了安全和事件管理 (SIEM) 系统，该服务会向您的 SIEM 系统发送警报详细信息。

有关详细信息，请参见 link:https://docs.netapp.com/us-en/bluexp-ransomware-protection/rp-use-alert.html["处理检测到的勒索软件警报"]。



=== 2025年6月9日



==== 着陆页更新

此版本包括对 BlueXP 勒索软件保护登陆页面的更新，使得开始免费试用和发现更加容易。



==== 准备演习更新

以前，您可以通过模拟对新示例工作负载的攻击来运行勒索软件就绪演练。借助此功能，您可以调查模拟攻击并恢复工作负载。使用此功能测试警报通知、响应和恢复。可以根据需要定期运行和安排这些演练。

在此版本中，您可以使用 BlueXP 勒索软件保护仪表板上的新按钮在测试工作负载上运行勒索软件准备演练，从而更轻松地模拟勒索软件攻击、调查其影响并有效地恢复工作负载，所有这些都在受控环境中完成。

现在，除了 NFS 工作负载之外，您还可以在 CIFS（SMB）工作负载上运行准备情况演练。

有关详细信息，请参见 https://docs.netapp.com/us-en/bluexp-ransomware-protection/rp-start-simulate.html["进行勒索软件攻击准备演练"]。



==== 启用 BlueXP 分类更新

在BlueXP  勒索软件保护服务中使用BlueXP  分类之前、您需要启用BlueXP  分类来扫描数据。对数据进行分类有助于您找到个人身份信息 (PII)，这可能会增加安全风险。

您可以在 BlueXP 勒索软件防护功能中对文件共享工作负载部署 BlueXP 分类。在“隐私暴露”列中，选择“识别暴露”选项。如果您已启用分类服务，此操作将识别暴露情况。否则，在此版本中，将出现一个对话框，其中包含部署 BlueXP 分类的选项。选择“部署”即可转到 BlueXP 分类服务登录页面，您可以在其中部署该服务。W

有关详细信息，请参阅 https://docs.netapp.com/us-en/bluexp-classification/task-deploy-cloud-compliance.html["在云中部署BlueXP分类"^]并在 BlueXP 勒索软件保护中使用服务，请参阅 https://docs.netapp.com/us-en/bluexp-ransomware-protection/rp-use-protect-classify.html["扫描具有BlueXP  分类的个人身份信息"] 。



=== 2025年5月13日



==== 报告BlueXP  勒索软件保护中不受支持的工作环境

在发现工作流期间、将鼠标悬停在支持或不支持的工作负载上时、BlueXP  勒索软件保护会报告更多详细信息。这将有助于您了解BlueXP  勒索软件保护服务未发现某些工作负载的原因。

服务不支持工作环境的原因有很多、例如、工作环境中的ONTAP版本可能低于所需版本。将鼠标悬停在不受支持的工作环境上时、工具提示会显示原因。

您可以在初始发现期间查看不受支持的工作环境、也可以从中下载结果。您还可以通过设置页面中的*工作负载发现*选项查看发现结果。

有关详细信息，请参见 https://docs.netapp.com/us-en/bluexp-ransomware-protection/rp-start-discover.html["在BlueXP勒索软件保护中发现工作负载"]。



=== 2025年4月29日



==== 支持适用于NetApp ONTAP 的Amazon FSX

此版本支持Amazon FSx for NetApp ONTAP。此功能可帮助您通过BlueXP  勒索软件保护来保护FSx for ONTAP工作负载。

FSx for ONTAP是一项完全托管的服务、可在云中提供NetApp ONTAP存储的强大功能。它可提供与内部环境相同的特性、性能和管理功能、并具有原生AWS服务的灵活性和可扩展性。

对BlueXP  勒索软件保护工作流进行了以下更改：

* 发现功能包括FSx for ONTAP 9.15工作环境中的工作负载。
* "保护"选项卡显示FSx for ONTAP环境中的工作负载。在此环境中、您应使用FSx for ONTAP备份服务执行备份操作。您可以使用BlueXP  勒索软件保护快照还原这些工作负载。
+

TIP: 无法在BlueXP  中为在FSx for ONTAP上运行的工作负载设置备份策略。在Amazon FSx for NetApp ONTAP中设置的任何现有备份策略保持不变。

* 警报事件显示了适用于ONTAP的新FSx工作环境。


有关详细信息，请参见 https://docs.netapp.com/us-en/bluexp-ransomware-protection/concept-ransomware-protection.html["了解BlueXP  勒索软件防护和工作环境"]。

有关支持的选项的信息，请参阅 https://docs.netapp.com/us-en/bluexp-ransomware-protection/rp-reference-limitations.html["BlueXP  勒索软件保护限制"]。



==== 需要 BlueXP 访问角色

您现在需要以下访问角色之一来查看、发现或管理 BlueXP 勒索软件防护：组织管理员、文件夹或项目管理员、勒索软件防护管理员或勒索软件防护查看器。

https://docs.netapp.com/us-en/bluexp-setup-admin/reference-iam-predefined-roles.html["了解所有服务的 BlueXP 访问角色"^](英文)



=== 2025年4月14日



==== 就绪演练报告

在此版本中、您可以查看勒索软件攻击就绪演练报告。通过准备工作演练、您可以模拟对新创建的示例工作负载的勒索软件攻击。然后、调查模拟的攻击并恢复示例工作负载。此功能通过测试警报通知、响应和恢复过程、帮助您了解在发生实际勒索软件攻击时您已做好准备。

有关详细信息，请参见 https://docs.netapp.com/us-en/bluexp-ransomware-protection/rp-start-simulate.html["进行勒索软件攻击准备演练"]。



==== 新的基于角色的访问控制角色和权限

以前、您可以根据用户的职责为其分配角色和权限、这有助于您管理用户对BlueXP  勒索软件保护的访问。在此版本中、BlueXP  勒索软件保护新增了两个角色、并更新了权限。新角色包括：

* 勒索软件保护管理员
* 勒索软件保护查看器


有关权限的详细信息，请参见 https://docs.netapp.com/us-en/bluexp-ransomware-protection/rp-reference-roles.html["BlueXP  勒索软件保护基于角色的功能访问"]。



==== 付款改进

此版本对付款流程进行了多项改进。

有关详细信息，请参见 https://docs.netapp.com/us-en/bluexp-ransomware-protection/rp-start-licenses.html["设置许可和付款选项"]。



== 修复

BlueXP修复服务已于2024年4月22日删除。



== Replication



=== 2022年9月18日



==== 适用于ONTAP 到Cloud Volumes ONTAP 的FSX

现在、您可以将适用于ONTAP 的Amazon FSx文件系统中的数据复制到Cloud Volumes ONTAP。

https://docs.netapp.com/us-en/bluexp-replication/task-replicating-data.html["了解如何设置数据复制"]。



=== 2022年7月31日



==== FSX for ONTAP 作为数据源

现在、您可以将数据从适用于ONTAP 的Amazon FSX文件系统复制到以下目标：

* 适用于 ONTAP 的 Amazon FSX
* 内部 ONTAP 集群


https://docs.netapp.com/us-en/bluexp-replication/task-replicating-data.html["了解如何设置数据复制"]。



=== 2021年9月2日



==== 支持适用于 ONTAP 的 Amazon FSX

现在，您可以将数据从 Cloud Volumes ONTAP 系统或内部 ONTAP 集群复制到适用于 ONTAP 的 Amazon FSX 文件系统。

https://docs.netapp.com/us-en/bluexp-replication/task-replicating-data.html["了解如何设置数据复制"]。



== 软件更新



=== 2025年5月12日



==== 需要 BlueXP 访问角色

您现在需要以下访问角色之一来安装软件更新：*组织管理员*、*文件夹或项目管理员*、*存储管理员*、*存储查看者*或*存储运行状况专家*。具有存储查看者角色的用户拥有与软件更新相关的各种权限，但无法安装软件更新。 link:https://docs.netapp.com/us-en/bluexp/concept-iam-predefined-roles.html["了解 BlueXP 访问角色。"^]



=== 2025年4月2日



==== 已缓解风险

现在、您可以在BlueXP  软件更新的摘要部分中查看操作系统更新可缓解的风险总数。这样、用户就可以评估其安装基础上的安全性和稳定性改进。



=== 2024年8月7日



==== ONTAP更新

BlueXP  软件更新服务通过降低风险并确保客户能够充分利用ONTAP功能、为用户提供无缝的更新体验。

详细了解 link:https://docs.netapp.com/us-en/bluexp-software-updates/get-started/software-updates.html["BlueXP  软件更新"]。



== StorageGRID



=== 2025年5月12日



==== 需要BlueXP访问角色

现在，您需要以下访问角色之一来查看、发现或管理BlueXP中的StorageGRID ：*组织管理员*、*文件夹或项目管理员*、*存储管理员*或*存储健康专家*。 link:https://docs.netapp.com/us-en/bluexp/reference-iam-predefined-roles.html["了解 BlueXP 访问角色。"^]



=== 2024年8月7日



==== 新的高级视图

从StorageGRID 11.8开始、您可以使用熟悉的网格管理器界面从BlueXP  管理StorageGRID系统。

https://docs.netapp.com/us-en/bluexp-storagegrid/task-administer-storagegrid.html["了解如何使用高级视图管理StorageGRID"](英文)



==== 能够审核和批准StorageGRID管理接口证书

现在、您可以在从BlueXP  发现StorageGRID系统时查看和批准StorageGRID管理接口证书。您还可以在发现的网格上查看和批准最新的StorageGRID管理接口证书。

https://docs.netapp.com/us-en/bluexp-storagegrid/task-discover-storagegrid.html["了解如何在系统发现期间查看和批准服务器证书。"]



=== 2022年9月18日



==== 支持StorageGRID

现在、您可以直接从BlueXP发现StorageGRID 系统。通过发现StorageGRID 、您可以全面了解混合多云中的数据。



== 分层



=== 2023年8月9日



==== 使用自定义前缀作为分段名称

过去、在定义存储分段名称时、您需要使用默认的"光纤 池"前缀、例如_Fabric池bucket1_。现在、您可以在为存储分段命名时使用自定义前缀。只有在将数据层到Amazon S3时、此功能才可用。 https://docs.netapp.com/us-en/bluexp-tiering/task-tiering-onprem-aws.html#prepare-your-aws-environment["了解更多信息。"]。



==== 在所有BlueXP连接器中搜索集群

如果使用多个连接器管理环境中的所有存储系统、则要实施分层的某些集群可能位于不同的连接器中。如果您不确定是哪个Connector管理某个集群、可以使用BlueXP分层跨所有连接器进行搜索。 https://docs.netapp.com/us-en/bluexp-tiering/task-managing-tiering.html#search-for-a-cluster-across-all-bluexp-connectors["了解更多信息。"]。



=== 2023年7月4日



==== 调整带宽以传输非活动数据

激活BlueXP分层后、ONTAP可以使用无限的网络带宽将非活动数据从集群中的卷传输到对象存储。如果您发现分层流量正在影响正常用户工作负载、则可以限制传输期间可使用的带宽量。 https://docs.netapp.com/us-en/bluexp-tiering/task-managing-tiering.html#changing-the-network-bandwidth-available-to-upload-inactive-data-to-object-storage["了解更多信息。"](英文)。



==== 通知中心中显示的层事件

现在、如果集群对其冷数据(包括未分层任何数据的集群)的分层不足20%、则分层事件"将其他数据从集群<name>分层到对象存储以提高存储效率"将显示为通知。

此通知是一个"建议"、可帮助您提高系统效率并节省存储成本。它提供了指向的链接 https://bluexp.netapp.com/cloud-tiering-service-tco["BlueXP分层总拥有成本和节省量计算器"^] 以帮助您计算成本节省。



=== 2023年4月3日



==== 已删除许可选项卡

已从BlueXP分层界面中删除许可选项卡。现在、您可以从BlueXP分层内部部署信息板访问按需购买(PAYGO)订阅的所有许可。此外、还提供了一个从该页面到BlueXP数字钱包的链接、可用于查看和管理任何BlueXP分层自带许可证(BYOL)。



==== 分层选项卡已重命名和更新

"集群信息板"选项卡已重命名为"集群"、"内部概述"选项卡已重命名为"内部部署信息板"。这些页面添加了一些信息、可帮助您评估是否可以通过其他分层配置优化存储空间。



== 卷缓存



=== 2023年6月4日



==== 卷缓存

卷缓存是ONTAP 9软件的一项功能、它是一项远程缓存功能、可简化文件分发、通过使资源更靠近用户和计算资源所在位置来减少WAN延迟、并降低WAN带宽成本。卷缓存可在远程位置提供永久性可写卷。您可以使用BlueXP卷缓存加快数据访问速度、或者从访问量较多的卷卸载流量。缓存卷非常适合读取密集型工作负载、尤其是客户端需要重复访问相同数据的情况。

借助BlueXP卷缓存、您可以缓存云、尤其是Amazon FSx for NetApp ONTAP、Cloud Volumes ONTAP以及作为工作环境的内部环境。

link:https://docs.netapp.com/us-en/bluexp-volume-caching/get-started/cache-intro.html["详细了解BlueXP卷缓存"]。



== 工作负载工厂



=== 2025年6月29日



==== 更新数据库的权限

现在，数据库在只读模式下具有以下权限：  `cloudwatch:GetMetricData` 。

https://docs.netapp.com/us-en/workload-setup-admin/permissions-reference.html#change-log["权限引用更改日志"]



==== BlueXP 工作负载工厂通知服务支持

BlueXP 工作负载工厂通知服务支持工作负载工厂向 BlueXP 警报服务或 Amazon SNS 主题发送通知。发送到 BlueXP 警报的通知会显示在 BlueXP 警报面板中。当工作负载工厂向 Amazon SNS 主题发布通知时，该主题的订阅者（例如人员或其他应用程序）会在为该主题配置的终端节点上收到通知（例如电子邮件或短信）。

https://docs.netapp.com/us-en/workload-setup-admin/configure-notifications.html["配置 BlueXP 工作负载工厂通知"]



=== 2025年5月4日



==== CloudShell自动完成支持

使用BlueXP  Workload Factory CloudShell时、您可以开始键入命令、然后按Tab键查看可用选项。如果存在多种可能、命令行界面将显示建议列表。此功能可最大限度地减少错误并加快命令执行速度、从而提高工作效率。



==== 更新了权限术语

工作负载工厂用户界面和文档现在使用“只读”来指代读取权限，使用“读/写”来指代自动化权限。



=== 2025年3月30日



==== CloudShell会报告ONTAP命令行界面命令的AI生成的错误响应

使用CloudShell时、每次发出ONTAP命令行界面命令并出现错误时、您都可以获得AI生成的错误响应、其中包括故障说明、故障原因和详细解决方案。

link:https://docs.netapp.com/us-en/workload-setup-admin/use-cloudshell.html["使用CloudShell"]



==== IAM：SimulatePermission Policy权限更新

现在、当您添加其他AWS帐户凭据或添加新工作负载功能(例如GenAI工作负载)时、您可以从工作负载出厂控制台管理此 `iam:SimulatePrincipalPolicy`权限。

link:https://docs.netapp.com/us-en/workload-setup-admin/permissions-reference.html#change-log["权限引用更改日志"]



=== 2025年2月2日



==== BlueXP  工作负载出厂控制台中提供了CloudShell

您可以从BlueXP  工作负载出厂控制台中的任何位置访问CloudShell。通过CloudShell、您可以使用在BlueXP  帐户中提供的AWS和ONTAP凭据、并在类似于Shell的环境中执行AWS命令行界面命令或ONTAP命令行界面命令。

link:https://docs.netapp.com/us-en/workload-setup-admin/use-cloudshell.html["使用CloudShell"]



==== 更新数据库的权限

现在，以下权限在_read_模式下可用于数据库： `iam:SimulatePrincipalPolicy`。

link:https://docs.netapp.com/us-en/workload-setup-admin/permissions-reference.html#change-log["权限引用更改日志"]
