= 添加了将卷备份到S3配置的ONTAP系统上的分段的支持
:allow-uri-read: 


[IMPORTANT]
====
* 由于增强了安全性、您的Connector现在需要通过出站Internet访问其他端点、以便在公有云环境中管理备份和恢复资源。如果此端点尚未添加到防火墙的"允许"列表中、您将在UI中看到有关"服务不可用"或"无法确定服务状态"的错误：
+
\https://netapp-cloud-account.auth0.com

* 现在、如果您使用的是"CVO专业版"软件包、可以将Cloud Volumes ONTAP和BlueXP备份和恢复捆绑在一起、则需要订阅备份和恢复PAYGO。过去不需要这样做。符合条件的Cloud Volumes ONTAP系统的备份和恢复订阅不会产生任何费用、但在任何新卷上配置备份时需要此费用。


====


=== 添加了将卷备份到S3配置的ONTAP系统上的分段的支持

现在、您可以使用已配置简单存储服务(S3)的ONTAP系统将卷备份到对象存储。内部ONTAP系统和Cloud Volumes ONTAP系统均支持此功能。在云部署和不能访问Internet的内部位置("私有"模式部署)支持此配置。

https://docs.netapp.com/us-en/bluexp-backup-recovery/task-backup-onprem-to-ontap-s3.html["了解更多信息。"]。



=== 现在、您可以将受保护卷中的现有Snapshot包含在备份文件中

过去、您可以将读写卷中的现有Snapshot副本包含在初始备份文件中并存储到对象存储中(而不是从最新的Snapshot副本开始)。只读卷(数据保护卷)中的现有Snapshot副本不包含在此备份文件中。现在、您可以选择在"DP"卷的备份文件中包含较早的Snapshot副本。

备份向导会在备份步骤结束时显示一条提示、您可以在其中选择这些"现有快照"。



=== BlueXP备份和恢复不再支持对未来添加的卷进行自动备份

以前、您可以选中备份向导中的复选框、将选定备份策略应用于添加到集群中的所有未来卷。根据用户反馈以及未使用此功能、此功能已被删除。您需要手动为添加到集群中的任何新卷启用备份。



=== "作业监控"页面已更新、新增了一些功能

现在、"作业监控"页面提供了与3-2-1备份策略相关的详细信息。该服务还提供与备份策略相关的其他警报通知。

"备份生命周期"类型筛选器已重命名为"保留"。使用此筛选器可跟踪备份生命周期并确定所有备份副本的到期日期。"保留"作业类型会捕获在受BlueXP备份和恢复保护的卷上启动的所有Snapshot删除作业。

https://docs.netapp.com/us-en/bluexp-backup-recovery/task-monitor-backup-jobs.html["了解有关更新的作业监控器的更多信息"]。
